google/zerocopy

src/lib.rs

Currently, three tests are failing with the latest nightly version of miri: `test_eq`, `test_ne`, `test_ord`.
Example output:
```bash
➜  zerocopy git:(main) ✗ cargo miri test -- test_ord
Preparing a sysroot for Miri (target: x86_64-unknown-linux-gnu)... done
Finished test [unoptimized + debuginfo] target(s) in 0.01s
Running unittests src/lib.rs (target/miri/x86_64-unknown-linux-gnu/debug/deps/zerocopy-3f8b570858445ddd)
running 1 test
test tests::test_ord ... FAILED
failures:
---- tests::test_ord stdout ----
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:2945:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
tests::test_ord
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 31 filtered out
error: …
```

Fix tests crashing with miri due to misalignment.

---

src/lib.rs

This helps with #7 , but doesn't necessarily close it (might be more places that should be inlined).
This PR adds the `#[inline]` attr to some the `ByteSlice` and `ByteSliceMut` trait impls, along with the `aligned_to` util fn, which otherwise seem to not get inlined, though they probably should. Tested this on yesterday's nightly, and latest stable. Even `lto = "fat"` and `codegen-units = 1` weren't helpful here.
I only saw concrete need for inlining in the `ByteSlice` impl for `&[u8]`, but added it for the rest of the impls because it seemed likely they might suffer from the same thing.
The second commit in this PR (which is independent from the first one) just coalesces `ByteSlice::as_ptr` and `ByteSliceMut::as_mut_ptr` into provided default impls on the trait declarations. This allows …

Inline more small functions.

---

.github/workflows/ci.yml
src/lib.rs

The alignment tests relied on the fact that the pointer width is 8 bytes, which is not the case for i686.
Fix the alignment tests so that they work on targets with pointer width of 4 or even 2 bytes.
Fixes #21

Fix alignment tests for targets with pointer width < 8 bytes

---

.github/workflows/ci.yml
src/lib.rs

The tests for the as_bytes() method assumed that bytes are stored in little endian order, which is not the case for PowerPC. Fix the alignment tests so that they work on both little and big endian targets.
Fixes #23

Fix as_bytes() test for big endian targets

---

src/lib.rs

Refactored map_zeroed & map_prefix_tuple_zeroed's for-loops with the [u8]::fill method.
Resolves #38

Refactor zeroing for loops with the [u8]::fill method

---

.github/workflows/ci.yml

The `test_new_error()` test was disabled for i686 due to Issue #21. This issue has since been fixed in #28, but the test was not re-enabled.

Re-enable test_new_error() for i686 target

---

zerocopy-derive/Cargo.toml

This update doesn't contain much in the way of feature improvements, but it does update some Cargo.toml metadata (including the repository link, which now actually points to this repository rather than to Fuchsia's repository, where this source code used to live).

[derive] Publish 0.3.2

---

.github/workflows/ci.yml

Add `-Z randomize-layout` flag to the CI when the tests are run in the nighlty toolchain. closes https://github.com/google/zerocopy/issues/56

[ci.yml] Add `randomize-layout` flag

---

.github/workflows/ci.yml

Addresses #43 by using the length of the feature string instead of the features themselves. This avoids the commas which were causing the issues and the key should be unique so long as the feature strings are of different lengths (which for the time being is the case).

Fix Rust Cache invalid key warning

---

Cargo.toml
src/lib.rs

Previously, `FromBytes::new_box_slice_zeroed` called `Layout::from_size_align_unchecked` with arguments that could overflow `isize`, which would violate its safety preconditions. In this change, we use the safe variant, which returns a `Result` which we can `.expect()`. Though I haven't benchmarked it, this likely has little impact on performance over the optimal code since optimal code would still need to perform the same bounds check that `from_size_align` is performing.

Fix unsoundness in FromBytes::new_box_slice_zeroed

---

src/byteorder.rs
src/lib.rs

Deny the `clippy::undocumented_unsafe_blocks` lint. Add SAFETY comments to some unsafe code, and add `#[allow(...)]` to the rest along with TODO comments to follow up.
This is the first step of #61.

Add some SAFETY comments, some TODO comments

---

.github/workflows/ci.yml
INTERNAL.md
README.md
src/lib.rs
tests/trybuild.rs
tests/ui-msrv/transmute-illegal.rs
tests/ui-msrv/transmute-illegal.stderr
tests/ui-stable/transmute-illegal.rs
tests/ui-stable/transmute-illegal.stderr
tests/ui/transmute-illegal.rs
tests/ui/transmute-illegal.stderr
zerocopy-derive/tests/trybuild.rs
zerocopy-derive/tests/ui-msrv/late_compile_pass.stderr

Make more functions and the `transmute!` macro const. This requires updating our MSRV to 1.61.0.
While we're doing this, document our MSRV in the crate root and our `README.md`.

Make more fns/macros const, update MSRV to 1.61.0

---

.github/workflows/ci.yml

Add check_msrv job to ci workflow. Checking the MSRV specified in all places mentioned in #39:
- Doc comment in src/lib.rs
- .github/workflows/ci.yml
- tests/trybuild.rs (added in https://github.com/google/zerocopy/pull/60, which hasn't merged as of this writing)
- zerocopy-derive/tests/trybuild.rs
When running locally this check works against #60 as well.
Resolves #39.

Add check_msrv job to ci workflow

---

src/lib.rs

Rename `AlignedBuffer<T, B>` to `Align<T, A>`. The former is a `B` aligned to at least `align_of::<T>()`, while the latter is a `T` aligned to at least `align_of::<A>()`. They're functionally equivalent, but the latter isn't documented in such a way that implies that it can only be used for buffers.

Replace AlignedBuffer with more general Align

---

.github/workflows/ci.yml

Add a dimension in the matrix for which crate we're testing. This allows us to simplify the rest of the configuration by removing separate steps for building/testing zerocopy-derive. It also allows us to run zerocopy-derive tests under Miri.

[CI] Use matrix to test zerocopy-derive

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/lib.rs
zerocopy-derive/Cargo.toml

Store MSRV in Cargo.toml package.rust-version key

---

.github/workflows/ci.yml
Cargo.toml

Use the names "msrv", "stable", and "nightly" in the test matrix, and then use a separate build step to resolve those names to particular toolchain versions stored in `Cargo.toml`. This makes it so that the names used in CI never change - you can always do, e.g.:
${{ matrix.toolchain == 'msrv' }}
...and an update to our MSRV will never cause that code to become out of sync. It also may open the door for future improvements in which we use the toolchain versions in `Cargo.toml` instead of hard-coded versions in some Rust source files, although this is speculative.

[CI] Use symbolic toolchain names in matrix

---

src/lib.rs
zerocopy-derive/src/lib.rs

The TODO was to use `#[rustversion::stable(<MSRV>)]` to conditionally emit `allow(unknown_lints)` only on MSRV. The theory was that unconditionally doing `allow(unknown_lints)` risks someone adding an invalid or typo'd lint and thinking they're getting a lint that's not actually having any effect. This risk is real, but probably not important enough to justify either a) taking a production dependency on another crate or, b) avoiding this dependency by writing our own `build.rs` file.

Remove TODO to use rustversion

---

zerocopy-derive/src/lib.rs
zerocopy-derive/tests/priv_in_pub.rs

This commit corrects outdated code comments in zerocopy-derive. As of Rust 1.59.0, it is no longer an error to name private types in the `where` clauses of public trait impls for public types.

[derive] document Rust changes to priv-in-pub lint

---

src/byteorder.rs

Add submodules which define type aliases for the `byteorder::*` types with a specific byte order type argument. This allows us to go from the somewhat clunky:
```rust
use byteorder::NetworkEndian;
use zerocopy::byteorder::U16;
#[derive(FromBytes, AsBytes, Unaligned)]
#[repr(C)]
struct UdpHeader {
src_port: U16<NetworkEndian>,
dst_port: U16<NetworkEndian>,
length: U16<NetworkEndian>,
checksum: U16<NetworkEndian>,
}
```
...to the less clunky:
```rust
use zerocopy::byteorder::network_endian::U16;
#[derive(FromBytes, AsBytes, Unaligned)]
#[repr(C)]
struct UdpHeader {
src_port: U16,
dst_port: U16,
length: U16,
checksum: U16,
}
```
Closes #100

[byteorder] Add submodules with byte order aliases

---

.github/workflows/ci.yml

[`actions-rs/toolchain`](https://github.com/actions-rs/toolchain) is not actively maintained and a number of warnings are thrown when ran. Some community efforts are made to revive the project but nothing has really materialized as of yet. [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain) does essentially the same thing except it is actively maintained and `dtolnay` is a very reputable member of the Rust community.
The switch is frictionless. 
For more information, you can take a look at [this](https://github.com/actions-rs/toolchain/issues/216) issue.

Switch from actions-rs/toolchain to dtolnay/rust-toolchain.

---

.github/workflows/ci.yml
Cargo.toml
INTERNAL.md
zerocopy-derive/Cargo.toml

Have zerocopy depend on an exact version of zerocopy-derive. See the note added to `INTERNAL.md` in this commit for a justification.
Closes #107

Have zerocopy depend exactly on derive version

---

Cargo.toml
generate-readme.sh

When using a standard SPDX license, Cargo.toml should only have the license field. `license-file` is for use when the license being used is nonstandard, per:
https://doc.rust-lang.org/cargo/reference/manifest.html

Cargo.toml: use `license` instead of `license-file`

---

src/lib.rs

Add FromBytes::new_vec_zeroed

---

zerocopy-derive/src/lib.rs
zerocopy-derive/tests/ui-msrv/late_compile_pass.stderr
zerocopy-derive/tests/ui-stable/late_compile_pass.stderr
zerocopy-derive/tests/ui/late_compile_pass.stderr

This cleans up some of the error messages without introducing any functional changes. This will also make it easier to enable deriving on generic types in the future.

Move field type bounds into where clauses

---

src/lib.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/tests/enum_as_bytes.rs
zerocopy-derive/tests/enum_from_bytes.rs
zerocopy-derive/tests/enum_unaligned.rs
zerocopy-derive/tests/struct_as_bytes.rs
zerocopy-derive/tests/struct_from_bytes.rs
zerocopy-derive/tests/struct_unaligned.rs
zerocopy-derive/tests/ui-msrv/derive_transparent.rs
zerocopy-derive/tests/ui-msrv/derive_transparent.stderr
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-msrv/union.stderr
zerocopy-derive/tests/ui-stable/derive_transparent.rs
zerocopy-derive/tests/ui-stable/derive_transparent.stderr
zerocopy-derive/tests/ui-stable/struct.stderr
zerocopy-derive/tests/ui-stable/union.stderr
zerocopy-derive/tests/ui/derive_transparent.rs
zerocopy-derive/tests/ui/derive_transparent.stderr
zerocopy-derive/tests/ui/late_compile_pass.rs
zerocopy-derive/tests/ui/struct.rs
zerocopy-derive/tests/ui/struct.stderr
zerocopy-derive/tests/ui/union.rs
zerocopy-derive/tests/ui/union.stderr
zerocopy-derive/tests/union_as_bytes.rs
zerocopy-derive/tests/union_from_bytes.rs
zerocopy-derive/tests/union_unaligned.rs
zerocopy-derive/tests/util.rs

Fixes #9. Depends on #119 because the generated generic bounds cannot be used in a constant context.

Transparent generic structs

---

src/lib.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/tests/struct_as_bytes.rs
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-stable/struct.stderr
zerocopy-derive/tests/ui/struct.stderr

Unify our handling of `repr(packed)` and `repr(transparent)` when deriving `AsBytes`, and bring error messages up to date with the fact that we support both of these reprs on generic structs.
Closes #127

[derive] Clean up AsBytes support on repr(packed)

---

Cargo.toml
src/lib.rs
zerocopy-derive/Cargo.toml
zerocopy-derive/src/lib.rs
zerocopy-derive/tests/struct_as_bytes.rs
zerocopy-derive/tests/struct_from_bytes.rs
zerocopy-derive/tests/struct_unaligned.rs
zerocopy-derive/tests/ui-msrv/derive_transparent.stderr
zerocopy-derive/tests/ui-msrv/late_compile_pass.stderr
zerocopy-derive/tests/ui-stable/derive_transparent.stderr
zerocopy-derive/tests/ui-stable/late_compile_pass.stderr
zerocopy-derive/tests/ui/derive_transparent.rs
zerocopy-derive/tests/ui/derive_transparent.stderr
zerocopy-derive/tests/ui/late_compile_pass.rs
zerocopy-derive/tests/ui/late_compile_pass.stderr
zerocopy-derive/tests/util.rs

In order to test this support, add a new `Unsized` type in zerocopy's
`test` module. Use this to test the derive and also to test `AsBytes`'s
methods in `test_as_bytes_methods`. These tests supersede the previous
unsized tests, which used slices, and have been removed.
While we're here, expand `test_as_bytes_methods` to test the `write_to`,
`write_to_prefix`, and `write_to_suffix` methods, which were not
previously tested.

[derive] Support deriving on unsized types

---

src/byteorder.rs

This was previously a hand-rolled impl, but now that our `AsBytes` derive supports generic `repr(transparent)` types, we can use the derive instead.

[byteorder] Derive AsBytes for byteorder types

---

Cargo.toml
src/lib.rs

Previously, impls of the `FromBytes`, `AsBytes`, and `Unaligned` traits were spread across a number of inconsistent and hard-to-follow macro invocations. This commit cleans that up by introducing a single macro and a single section of `lib.rs` to hold macro invocations.
This commit also adds some safety comments, but there are still some left as TODOs. Note that, since this commit does not add or remove any trait impls (see `test_impls` for a confirmation that the exact set of impls are tested), these TODOs are acceptable to add in this commit; this commit moves us strictly forward in terms of safety comment coverage.

Clean up trait impls, add some safety comments

---

src/lib.rs

Add the following impls:
- `str: Unaligned`
- `NonZeroU8: Unaligned`
- `NonZeroI8: Unaligned`
- `Option<NonZeroU8>: Unaligned`
- `Option<NonZeroI8>: Unaligned`
- `MaybeUninit<T>: Unaligned` where `T: Unaligned`
Previously, `unsafe_impl!` special-cased `Unaligned` and emitted a static assertion that the type in question actually had alignment 1. Since this used `core::mem::align_of`, which only works for `Sized` types, it was incompatible with adding an impl of `Unaligned` for `str` in this commit. In order to avoid this issue, this commit removes that special-casing, and introduces a new `assert_unaligned!` macro. Existing `Unaligned` implementations are modified to also call `assert_unaligned!`. `assert_unaligned!(str)` is not used since `str: !Unaligned`.

Add new trait impls

---

src/lib.rs
zerocopy-derive/Cargo.toml
zerocopy-derive/tests/enum_as_bytes.rs
zerocopy-derive/tests/enum_from_bytes.rs
zerocopy-derive/tests/enum_unaligned.rs
zerocopy-derive/tests/hygiene.rs
zerocopy-derive/tests/struct_as_bytes.rs
zerocopy-derive/tests/struct_from_bytes.rs
zerocopy-derive/tests/struct_unaligned.rs
zerocopy-derive/tests/ui-msrv/derive_transparent.stderr
zerocopy-derive/tests/ui-stable/derive_transparent.stderr
zerocopy-derive/tests/ui/derive_transparent.rs
zerocopy-derive/tests/ui/derive_transparent.stderr
zerocopy-derive/tests/union_as_bytes.rs
zerocopy-derive/tests/union_from_bytes.rs
zerocopy-derive/tests/union_unaligned.rs
zerocopy-derive/tests/util.rs

Use the `static_assertions` crate's `assert_impl_all!` and `assert_not_impl_any!` macros instead of our own hand-rolled code.
This also fixes a (previously unknown) bug in
`test_impls::assert_impls!` in which a missing `?Sized` bound made it so that negative impl tests would do nothing for unsized types.

Use static_assertions to assert trait impls

---

src/lib.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/tests/enum_from_zeroes.rs
zerocopy-derive/tests/ui-msrv/enum.stderr
zerocopy-derive/tests/ui-stable/enum.stderr
zerocopy-derive/tests/ui/enum.rs
zerocopy-derive/tests/ui/enum.stderr

Closes #30. @joshlf the wording of [the reference](https://doc.rust-lang.org/reference/items/enumerations.html#custom-discriminant-values-for-fieldless-enumerations) seems to imply that we can derive `FromZeroes` on enums without an explicit repr. Do you feel comfortable doing that?

Relax requirements for deriving `FromZeroes` on enums

---

tests/ui-msrv/transmute-illegal.stderr
tests/ui-stable/transmute-illegal.stderr
tests/ui/transmute-illegal.rs
tests/ui/transmute-illegal.stderr

This removes one source of errors which clutters the `.stderr` files and is a source of noise when the compiler's error output changes.

Add `fn main` to UI test files

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/lib.rs
zerocopy-derive/Cargo.toml

The feature is on by default, but allows consumers to avoid the dependency on the `byteorder` crate if they wish.

Put the byteorder module behind a feature flag

---

src/lib.rs

Move now-stable aarch64 types to "simd" feature

---

.github/workflows/ci.yml

Set the `jobs.build_test.strategy.fail-fast` GitHub CI configuration option to `false`, ensuring that other CI jobs continue executing even when one has failed. This helps speed up development by surfacing more errors at a time.

[ci] Fail fast on CI errors

---

src/lib.rs

Adds the `Unalign::update` method, which allows updating an `Unalign` in-place via a callback. This works by temporarily moving the `Unalign` into the local stack frame in order to call the callback.
Closes #206

Add Unalign::update method

---

src/byteorder.rs
src/lib.rs

While `LayoutVerified` is technically a descriptive name, it doesn't give much of a hint as to what the type's intended use is. The way it is used in practice is as a sort of "smart" reference - the only difference from a native reference (`&` or `&mut`) is that it is generic over the mutability of the byte slice from which it was constructed. Thus, `Ref` is a more helpful and informative name.
Closes #68
cc @kupiakos

Rename LayoutVerified to Ref

---

src/lib.rs

In `FromBytes` and `AsBytes`, we have some methods which took a `B: ByteSlice` or `B: ByteSliceMut` bound which was unnecessary. In this commit, we simplify those methods by just taking `&[u8]` or `&mut [u8]` instead. This simplifies the API and also may reduce monomorphization bloat for some users.

Replace generic ByteSlices with concrete slices

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/lib.rs

Cherry-pick 0fbc928

---

src/byteorder.rs

Fix Clippy as_underscore lint

---

src/lib.rs

Move now-stable aarch64 types to "simd" feature (#172)

---

src/lib.rs

Adds the `Unalign::update` method, which allows updating an `Unalign` in-place via a callback. This works by temporarily moving the `Unalign` into the local stack frame in order to call the callback.
Closes #206

Add Unalign::update method (#212)

---

Cargo.toml
README.md
src/lib.rs

This feature caused breakage in 0.6.2 (see [1] for details). This commit removes the feature and makes the `byteorder` module present unconditionally. This will not be ported to 0.7.0, which will contain the `byteorder` feature.
[1] https://github.com/google/zerocopy/issues/228#issuecomment-1668506529

[0.6.x] Remove byteorder feature

---

src/lib.rs

This should help make the transition to 0.7.0 easier, as code which currently uses `LayoutVerified` will get a deprecation warning instead of a (much less helpful) "not found" error.

Add deprecated LayoutVerified type alias

---

src/lib.rs

Document some unsafe blocks

---

Cargo.toml
src/lib.rs
tests/trybuild.rs
tests/ui-nightly/transmute-illegal.stderr
tests/ui-stable/transmute-illegal.stderr
zerocopy-derive/tests/trybuild.rs
zerocopy-derive/tests/ui-nightly/derive_transparent.stderr
zerocopy-derive/tests/ui-stable/derive_transparent.stderr
zerocopy-derive/tests/ui-stable/enum.stderr

It turned out that there were only a few lines of code that required our MSRV to be as high as it was before this commit (1.65.0), and those lines were easy to modify to be compatible with this new MSRV.
Note that this requires introducing defensive code to `FromZeroes::new_box_slice_zeroed` in order to sidestep a bug in `Layout::from_size_align` that was present through 1.64.0.

Reduce MSRV to 1.61.0 (#234)

---

.github/workflows/ci.yml

GitHub automatically evaluates the content of an if conditional as  an expression, so the `${{ ... }}` braces are unnecesssary.

[CI] Don't use expression syntax in if conditionals

---

.github/workflows/scorecard.yml

Grant Scorecard the ability to read certain configuration in order to be able to perform a more detailed security analysis. This does not grant it the ability to modify any configuration.
Makes progress on #230.

[CI] Grant Scorecard more permissions

---

zerocopy-derive/src/lib.rs
zerocopy-derive/src/repr.rs

This lint isn't an issue on our pinned nightly, but it is on more recent nightlies as of this writing. Might as well fix it now.

Fix an uncoming Clippy lint

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/byteorder.rs
src/lib.rs
src/macros.rs
tests/trybuild.rs
tests/ui-msrv/invalid-impls/invalid-impls.rs
tests/ui-msrv/invalid-impls/invalid-impls.stderr
tests/ui-nightly/invalid-impls/invalid-impls.rs
tests/ui-nightly/invalid-impls/invalid-impls.stderr
tests/ui-stable/invalid-impls/invalid-impls.rs
zerocopy-derive/Cargo.toml

This requires a few changes to accomodate:
- We still want to be able to derive zerocopy traits on our own types so
that we can rely on it to validate the soundness of those impls for
us. That means that, when the `derive` feature is enabled, we still
use custom derives, but when it's disabled, we implement traits
manually. However, we also need to ensure that our manual trait impls
have the correct bounds required in order for those impls to be sound.
In order to ensure this, we introduce an `impl_or_verify!` macro
which, when building with `derive` enabled, verifies that the manual
impl matches the one emitted by our custom derive.
- Since some doc examples use custom derives, we can no longer run doc
tests unconditionally in CI - when the `derive` feature is disabled,
doc tests fail. …

Make zerocopy-derive an optional dependency

---

src/lib.rs

For `T: Unaligned`, `Unalign<T>: DerefMut`. Using that impl will usually be faster and more ergonomic than using `update`.
Closes #262

Unalign::update docs suggest DerefMut

---

src/lib.rs

Don’t compile derive_util unless needed

---

.github/workflows/ci.yml
generate-readme.sh

Fixes #225
The reason `set -e` failed to interrupt the workflow is due to the output redirection to `jq`. Since `jq` returns a value of 0, indicating success, the script continues to execute. You can try running these scripts locally to gain insight into the issue.
To illustrate:
Script without interruption:
```sh
set -e
function pkg-meta {
cargo metadata --format-version 1 | jq -r ".packages[] | select(.name\
== \"zerocopy\").$1"
}
ZC_TOOLCHAIN=\"$(pkg-meta 'metadata.ci.\"pinned-nightly\"')\"
echo \"Discovered that the nightly toolchain is $ZC_TOOLCHAIN\"
echo \"ZC_TOOLCHAIN=$ZC_TOOLCHAIN\"
```
Script with interruption:
```sh
set -e
function pkg-meta {
cargo metadata --format-version 1"
}
ZC_TOOLCHAIN=\"$(pkg-meta 'metadata.ci.\"pinned-nightly\"')\"
echo \"Discovered that the nightly …
```

Cargo check before get the metadata

---

.github/workflows/ci.yml

Run Miri tests under both stacked borrows and tree borrows.

[CI] Run Miri tests under both borrow models

---

src/lib.rs

For each of our unsafe traits, clarify who can skip reading the Safety section.
For each of our unsafe traits (except for `Unaligned`):
- Clarify that it must be sound to construct `&[u8]` and `&T` to the same memory region (this addresses #8)
- Clarify that, in order to implement the trait, the type's fields need to satisfy the same requirements, but don't actually need to implement the trait
- Clarify that, in order to implement the trait, the type must not contain any `UnsafeCell`s
Closes #8

Improve trait safety documentation

---

Cargo.toml
src/lib.rs
zerocopy-derive/Cargo.toml

Previously, we implemented `FromZeroes` and `FromBytes` for `MaybeUninit<T>` with no bound on `T`. This resulted in a soundness hole in which `T` - and thus `MaybeUninit<T>` - could contain an `UnsafeCell`, which is a violation of the contracts of `FromZeroes` and `FromBytes`.
This is a breaking change, but it's very unlikely to be one that code is currently relying on, especially given that the 0.7.x release train was published very recently. Thus, in this commit, we publish 0.7.3, and we will yank 0.7.{0,1,2} as soon as 0.7.3 is published.
Fixes #299

Restrict MaybeUninit trait impls to fix soundness

---

src/lib.rs

This TODO was anchored on #8, which was fixed in #283.

Remove TODO

---

.github/workflows/ci.yml
Cargo.toml

Cache the dependencies

---

.github/workflows/ci.yml

The caching introduced in #302 fixes the issue that this override was meant to address, so it's no longer necessary.

[CI] Remove CARGO_NET_RETRY override

---

src/lib.rs
src/macros.rs

Condense into fewer, more powerful match arms.

Simplify unsafe_impl! macro

---

src/byteorder.rs
src/lib.rs
src/macros.rs
src/wrappers.rs

This lint should catch every place that an `#[inline]` attribute could matter. This commit only addresses zerocopy, and does not change anything in zerocopy-derive.
Makes progress on #7

Deny clippy::missing_inline_in_public_items

---

src/macros.rs

The following is now supported:
```
safety_comment! {
/// SAFETY:
/// Safety comment here.
macro_invocation!();
macro_invocation!();
/// Previously, this comment (which appears after macro
/// invocations) was not supported.
macro_invocation!();
macro_invocation!();
}
```

[macros] safety_comment! permits multiple comments

---

src/macros.rs

Our traits define the `only_derive_is_allowed_to_implement_this_trait` method. It is `#[doc(hidden)]`, exists only as a speedbump to manual impls, and is presumably never called by users. It's a waste to have it marked as `#[inline]`.

Don't inline functions that are never called

---

src/lib.rs
src/macros.rs
src/util.rs

In its initial form, the `KnownLayout` trait encodes type layout information slightly more complex than can be gleaned from any arbitrary `T: ?Sized`. This allows it to support not just sized and slice types, but also "custom DSTs" (those with fixed-size fields followed by a trailing slice type). This is the first step to supporting various operations on arbitrary custom DSTs.

Add KnownLayout trait

---

Cargo.toml
src/byteorder.rs

While they take a trivial amount of time running natively, the `test_native_endian` and `test_non_native_endian` unit tests previously took a long time to execute on Miri, slowing down local development and CI. As of the writing of this commit message, I was experiencing execution times for each test of ~60s.
This commit optimizes those tests in two ways:
- Use a faster RNG
- When running under Miri (detected using `cfg!(miri)`), perform a single loop iteration rather than 1024
Using `time cargo miri test -- --skip ui`, I have benchmarked the execution time before this commit at ~2m36s and the time after this commit at ~8s.

[byteorder] Optimize tests; large impact on Miri

---

.github/workflows/ci.yml
cargo.sh

`cargo.sh` is a small utility that supports running Cargo with human-readable toolchain names that are mapped to the equivalent versions pinned in CI. It supports "msrv", "stable", and "nightly". It also supports a meta-toolchain, "all", which instructs it to run a command once with each of the three pinned toolchains.
In this commit, we replace the toolchain name-to-version resolution logic in CI with this command. This simplifies our CI configuration, and maintains the property that the code run in CI is the same code a developer would run on their local machine.
cc @djkoloski

[cargo.sh] Initial commit

---

Cargo.toml
tests/ui-msrv/invalid-impls/invalid-impls.stderr

Previously, we mistakenly omitted "derive" as one of the features to test on the MSRV and stable toolchains. As a result, our UI test .stderr files for the MSRV toolchain were stale.

[CI] Treat "derive" as a stable feature

---

.github/workflows/ci.yml
Cargo.toml
src/byteorder.rs
src/lib.rs

`cargo test --doc` and `cargo doc` now succeed on all feature
combinations.
Previously, we had a separate CI job step for running doc tests, and we
had doc tests disabled by default in `Cargo.toml`. Now, we can get rid
of the separate CI job, and we can get rid of the disablement in
`Cargo.toml`.

[docs] Docs and doctests succeed for all features

---

zerocopy-derive/Cargo.toml
zerocopy-derive/src/ext.rs
zerocopy-derive/src/lib.rs

Clean up the implementation, especially in `fn impl_block`. Make the following notable changes:
- Previously, `syn` didn't support parsing macro invocations in const generics without the `full` feature enabled. To avoid the compile-time overhead of that feature, we worked around it by constructing AST nodes manually. `syn` has since added support for this without requiring the `full` feature, so we make use of it.
- We used to need to split types into those that transatively depended upon type generics (like `[T; 2]`) and those that didn't (like `[u8; 2]`). We made a change in #119 that made this distinction irrelevant, but we never removed the code to perform the split. In this commit, we remove that code. That code was the only reason we needed to enable `syn`'s `visit` feature, so we …

[derive] Simplify code, remove obsolete features

---

.github/workflows/ci.yml
cargo.sh
src/lib.rs
src/third_party/rust/LICENSE-APACHE
src/third_party/rust/LICENSE-MIT
src/third_party/rust/layout.rs
src/util.rs

Previously, `validate_cast_and_convert_metadata` incorrectly assumed
that, for slice DSTs, the trailing slice element would always have an
alignment at least as large as the outer type's alignment, and so there
would never be any padding added after the trailing slice. In this
commit, we rewrite `validate_cast_and_convert_metadata` to no longer
assume this behavior.
While we're here, we add the `test_validate_rust_layout` test, which
validates many of our assumptions about Rust's type layout against the
standard library to help catch mismatches like this in the future.

Fix bug in validate_cast_and_convert_metadata

---

src/lib.rs

Previously, we had logic to omit expensive formatting when running `test_validate_rust_layout` under Miri, but this was typo'd to have the opposite effect as intended - the expensive formatting would run /only/ when running under Miri. This commit fixes that typo, and as a result, the test in question runs fast enough that we can remove other logic designed to speed up execution only under Miri.
Closes #391

[miri] Optimize tests

---

.github/workflows/ci.yml
src/lib.rs

In #376, we introduced `test_validate_rust_layout`, which took a long time to run under Miri. In order to prevent it from consuming too much time in CI, we marked it as `#[cfg_attr(miri, ignore)]`, and configured CI to pass `-- --ignored` to Miri only a small percentage of the time.
This had the unintended side effect of running
`test_validate_cast_and_convert_metadata` under Miri. That test is marked as `#[cfg_attr(miri, ignore)]` for good reason - it takes far too long to run under Miri, and doesn't exercise any `unsafe` code, so doesn't benefit from Miri. Enabling this test has caused CI to timeout.
In the interim, in #395, we optimized `test_validate_rust_layout` so that it no longer takes an unreasonably long time to run under Miri. Thus, in this commit, we remove the …

[ci] Don't run ignored tests under Miri

---

src/lib.rs
src/util.rs

This function implements the operation more efficiently using bitmasking instead of division and multiplication. While LLVM is probably smart enough in practice to produce this sort of code, Kani (#378) has trouble with multiplication, and so this code is hopefully more Kani-friendly.
Closes #390

Add round_down_to_next_multiple_of_alignment

---

.github/workflows/ci.yml
tests/trybuild.rs
zerocopy-derive/tests/trybuild.rs

Mark UI tests as `#[cfg_attr(miri, ignore)]`. In CI, remove `-- --skip ui` from our Miri invocation.

[miri] Skip running UI tests

---

Cargo.toml
tests/trybuild.rs
testutil/Cargo.toml
testutil/src/lib.rs
zerocopy-derive/Cargo.toml
zerocopy-derive/tests/trybuild.rs

The `testutil` crate currently supports extracting pinned toolchain versions and comparing these to the toolchain version used to run the test. This is used to replace `#[rustversion::*]` attributes. While it adds more code, it also means that, in order to roll pinned toolchain versions, only the root `Cargo.toml` needs to be updated (previously, it was also necessary to update `tests/trybuild.rs` and `zerocopy-derive/tests/trybuild.rs`). This paves the way to automate the rolling of pinned toolchain versions (see #348).

[testutil] Initial commit

---

src/third_party/rust/layout.rs
src/util.rs

Uses kani to prove that `round_down_to_next_multiple_of_alignment` and `padding_needed_for` are equivalent to straightforward model implementations.

Prove correctness of layout len utilities with kani

---

.github/workflows/ci.yml

Fixes #344. Maybe. Only way to find out is to merge it, and then see if we can enable the merge queue.

[ci] configure CI to support merge queue

---

src/lib.rs

Update TODO comments which track adding safety comments to `unsafe` blocks which are missing them. Previously, we used #61 to track these. Now, we're using #429.

Refactor `unsafe` blocks; update TODO comments

---

Cargo.toml
src/byteorder.rs
zerocopy-derive/Cargo.toml

[byteorder] Implement `core::ops` traits

---

.github/workflows/roll-pinned-toolchain-versions.yml

CI uses the `rust-src` component to ensure stable output in our UI tests. This commit matches that behavior in our auto-roller to make sure that the PRs generated by it will pass CI.

[roll] Install rust-src component when rolling

---

README.md
src/lib.rs

document zerocopy's relationship to Project Safe Transmute

---

.github/workflows/ci.yml
src/byteorder.rs

Previously, we spuriously didn't pass our global `RUSTFLAGS` that are passed in other CI jobs. As a result, `-Dwarnings` is now used, which causes `byteorder::tests::test_ops_impls` to be recognized as unused. This is also fixed.

[ci][kani] Pass correct RUSTFLAGS

---

.github/workflows/ci.yml

MIPS targets have been consistently unavailable recently, which has blocked our ability to roll the nightly toolchain.

[ci] Don't test on MIPS

---

src/lib.rs

`new_slice_from_suffix()` has a bug and implemented exactly as `new_slice_from_prefix()`. Now part of buffer is chosen right.
Tests couldn't have caught because buffer was just zeros. Now buffer is not just zeros so that tests can prove correctness of `new_slice_from_suffix()`.

Fix Ref::new_slice_from_suffix()

---

src/lib.rs

In #506, a bug was discovered which `test_new_aligned_sized` did not previously catch. This commit improves that test to catch that bug.

Improve test_new_aligned_sized to catch more bugs

---

src/lib.rs

This builds on new documentation added in
https://github.com/rust-lang/rust/pull/115522.
Makes progress on #429

Improve ManuallyDoc safety comments

---

.github/workflows/ci.yml
src/lib.rs
src/macros.rs
src/util.rs

`Ptr` is like `NonNull`, but has many restrictions which make it so that using a `Ptr` in unsafe code requires much simpler soundness proofs. Notably, it supports a `try_cast_into<U>` method where `U: ?Sized + KnownLayout`, which is a building block of `TryFromBytes`.

Initial commit of `Ptr` type

---

clippy.toml
src/lib.rs
src/wrappers.rs

Set the following Clippy configuration variables to `true`:
- `accept-comment-above-statement`
- `accept-comment-above-attributes`

[clippy] Be more permissive with safety comments

---

Cargo.toml
src/lib.rs
zerocopy-derive/Cargo.toml

This PR does essentially three things:
1. Provides examples of `#[derive(FromZeroes)]` being used
2. Provides examples of using many of `FromZeroes`'s methods.
3. Separates the documentation of the safety conditions of `FromZeroes`, from the documentation of how `derive(FromZeroes)` performs its analysis.
If the model of this PR looks good, I'll also apply it to `FromBytes` and `AsBytes`.

improve `FromZeroes` documentation

---

cargo.sh
src/lib.rs

Previously, cargo.sh did not forward `RUSTFLAGS` from the ambient environment. Consequently, the `-Dwarnings` directive of our CI was mostly ignored.

[cargo.sh] forward `RUSTFLAGS`

---

src/byteorder.rs
src/lib.rs
src/macros.rs
src/util.rs
src/wrappers.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/tests/enum_known_layout.rs
zerocopy-derive/tests/hygiene.rs
zerocopy-derive/tests/priv_in_pub.rs
zerocopy-derive/tests/struct_known_layout.rs
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-nightly/struct.rs
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/struct.stderr
zerocopy-derive/tests/union_known_layout.rs
zerocopy-derive/tests/util.rs

[derive] Support KnownLayout for sized types

---

Cargo.toml
zerocopy-derive/Cargo.toml
zerocopy-derive/src/lib.rs

Makes progress on #553, although we still need to figure out how to reproduce the bug that caused that issue in the first place, and add a test that exercises the same behavior (ie, fails without this commit).

[derive] Emit #[allow(deprecated)] in derived code

---

src/lib.rs

One common complaint I receive is how onerous it is to convert from bytes to type references in zerocopy for simple cases. I fully agree; we don't use the `Ref` type in most of our code. `AsBytes::as_bytes` makes it easy to go from `&T` to `&[u8]`, so why is there such a dance to go the other way?
These helper methods intend to improve the developer experience. They follow the same naming and error handling scheme as `read_from`. I would rather these stay named as such until a refactor of `read_from` and `write_to` occurs to match - I find that consistency valuable.
These avoid a tuple return in `from_[suffix|prefix]`  - again for developer UX since we usually threw these out.
```rust
fn ref_from(bytes: &[u8]) -> Option<&Self> where Self: Sized;
fn ref_from_prefix(bytes: &[u8]) -> …
```

Add bytes to type reference helper methods to `FromBytes`

---

src/lib.rs

This corrects a docstring mistake made during editing, and adds a comment for the `[u8; 9]` as requested.
See #526. Sorry for not responding - I've been out with COVID!

Improve docs for #526

---

.github/workflows/roll-pinned-toolchain-versions.yml

Allow triggering manually from the GitHub web UI.

[roll-pinned-toolchain-versions] Allow manual trigger

---

Cargo.toml
src/macro_util.rs
src/util.rs

This macro will be used by the derive of KnownLayout for slice DSTs.

[macro_util] Add trailing_field_offset! macro

---

src/macro_util.rs

The `align_of!` macro uses `trailing_field_offset!` to compute the alignment of DSTs with minimum alignments up to 65536. By contrast, `core::mem::align_of` does not support DSTs.
We can use this for supplying the alignment argument required by `DstLayout::for_dst` (introduced by #541).

add `align_of!` for computing alignment of DSTs

---

Cargo.toml
zerocopy-derive/Cargo.toml

Enable all stable features on the Rust playground

---

.github/workflows/ci.yml

Deduplicate some logic.
Closes #307

[ci][check_versions] Refactor bash script

---

src/lib.rs

Implement KnownLayout, FromZeroes for raw pointers

---

src/lib.rs

[docs] Mark KnownLayout derive #[doc(hidden)]

---

src/lib.rs

Re-export derive macros separately, naming them explicitly rather than re-exporting them by glob (i.e., `pub use zerocoy_derive::*`). Previously, in #588, we attempted to shadow the glob import in order to mark `KnownLayout` as `#[doc(hidden)]`, but this had no effect (presumably, the fact that it was `#[doc(hidden)]` meant that it didn't shadow the glob import, at least from `rustdoc`'s perspective).
In this commit, we just import everything separately by name, which allows the `#[doc(hidden)]` attribute on the `KnownLayout` derive to have the intended effect.

[docs] Re-export derive macros separately

---

src/macro_util.rs

Add a comment explaining why we don't change core_reexport to `pub use core as core_reexport`.

[macro_util] Add comment to core_reexport

---

Cargo.toml
src/lib.rs
src/macros.rs
zerocopy-derive/Cargo.toml

For thin pointer types, `P` (`Box<T>`, `&T`, `&mut T`, and `NonNull<T>` where `T: Sized`), implement `FromZeroes` for `Option<P>`.
Release 0.7.25.
Closes #293

FromZeroes for Option<T> where T is subject to NPO

---

Cargo.toml
src/lib.rs
src/macros.rs
zerocopy-derive/Cargo.toml

Use the `doc(cfg(...))` syntax in more places when generating documentation:
- `impl<T> FromZeroes for Option<Box<T>>`
- trait impls for simd types
Release 0.7.26.
Closes #597
Here's what the new docs look like rendered:

[doc] Use doc(cfg(...)) in more places

---

src/lib.rs

https://github.com/rust-lang/reference/pull/1392 adds bit validity guarantees for numeric types. This commit makes use of those guarantees to provide stronger soundness justifications for some trait impls.
Closes #440

Safety comments quote new bit validity guarantees

---

src/lib.rs
src/util.rs
tests/ui-msrv/max-align.rs
tests/ui-msrv/max-align.stderr
tests/ui-nightly/max-align.rs
tests/ui-nightly/max-align.stderr
tests/ui-stable/max-align.rs
tests/ui-stable/max-align.stderr

`DstLayout::extend` is comparable to `alloc::Layout`, except that it additionally handles DSTs. This is the first of two steps needed for `DstLayout` to support an API in the form of:
```rust
// For illustrative purposes; `align` and `packed`
// can't actually be combined like this.
#[repr(C, align(2), packed(4))]
struct ReprCStruct<T, U, V> {
foo: Foo<T>,
bar: Bar<U>,
baz: Baz<V>,
}
impl<T, U, V> KnownLayout for ReprCStruct<T, U, V> {
const LAYOUT: DstLayout = {
use ::zerocopy::macro_utils::core_reexport::num::NonZeroUsize;
use ::zerocopy::DstLayout;
let min_align = NonZeroUsize::new(2); // or `None`, w/o `align`
let max_align = NonZeroUsize::new(4); // or `None`, w/o `packed`
DstLayout::for_type::<()>()
.extend(<Foo<T> as KnownLayout>::LAYOUT, max_align)
.extend(<Bar<T> as …
```

Add `DstLayout::extend`

---

src/lib.rs

`DstLayout::pad_to_align` is comparable to `alloc::Layout::pad_to_align`, except that it additionally handles DSTs. This is the second of two steps needed for `DstLayout` to support an API in the form of:
```rust
// For illustrative purposes; `align` and `packed`
// can't actually be combined like this.
#[repr(C, align(2), packed(4))]
struct ReprCStruct<T, U, V> {
foo: Foo<T>,
bar: Bar<U>,
baz: Baz<V>,
}
impl<T, U, V> KnownLayout for ReprCStruct<T, U, V> {
const LAYOUT: DstLayout = {
use ::zerocopy::macro_utils::core_reexport::num::NonZeroUsize;
use ::zerocopy::DstLayout;
let min_align = NonZeroUsize::new(2); // or `None`, w/o `align`
let max_align = NonZeroUsize::new(4); // or `None`, w/o `packed`
DstLayout::new(min_align)
.extend(<Foo<T> as KnownLayout>::LAYOUT, max_align) …
```

Add `DstLayout::pad_to_align`

---

src/lib.rs
src/macros.rs

Add impls of `TryFromBytes` for types for which we already implement `FromBytes`.
Makes progress on #5

Add T: TryFromBytes where T: FromBytes

---

src/util.rs

Since raw pointer slice casts are now guaranteed to preserve element count [1], we no longer need to separately store the byte length of a `Ptr`. Instead, we can compute it from the raw pointer field.
[1] https://github.com/rust-lang/reference/pull/1417

[util] Ptr doesn't track byte length separately

---

zerocopy-derive/src/lib.rs
zerocopy-derive/tests/enum_known_layout.rs
zerocopy-derive/tests/struct_as_bytes.rs
zerocopy-derive/tests/struct_from_bytes.rs
zerocopy-derive/tests/struct_from_zeroes.rs
zerocopy-derive/tests/struct_known_layout.rs
zerocopy-derive/tests/struct_unaligned.rs
zerocopy-derive/tests/union_from_bytes.rs
zerocopy-derive/tests/union_from_zeroes.rs
zerocopy-derive/tests/union_known_layout.rs

Previously, the derive was not stripping out inline bounds.
Fixes #653

Handle const generics and bounded lifetimes in derives

---

src/lib.rs

[docs] Fix typo in include_value! doc comment

---

src/lib.rs
src/util.rs

Implement `TryFromBytes` for `[T]`

---

zerocopy-derive/src/repr.rs
zerocopy-derive/tests/struct_as_bytes.rs
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-nightly/struct.rs
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/struct.stderr

`packed(N)` does not gaurantee no padding, but it doesn't prevent it either. This was previously supported.
This regressed in #643 (left out of the commit message because of the requirement not to link to review sites).

[derive] Fix AsBytes for `#[repr(C, packed(N))]`

---

POLICIES.md

[policies] Document yanking policy

---

Cargo.toml
README.md
src/lib.rs
zerocopy-derive/Cargo.toml

This backports https://github.com/google/zerocopy/pull/692 and releases it as 0.7.30.

[readme] Link to GitHub Releases (#692)

---

tests/ui-msrv/transmute-mut-src-generic.stderr
tests/ui-nightly/transmute-mut-src-generic.rs
tests/ui-nightly/transmute-mut-src-generic.stderr
tests/ui-stable/transmute-mut-src-generic.stderr
zerocopy-derive/tests/ui-msrv/derive_transparent.stderr
zerocopy-derive/tests/ui-msrv/enum.stderr
zerocopy-derive/tests/ui-msrv/late_compile_pass.stderr
zerocopy-derive/tests/ui-nightly/derive_transparent.rs
zerocopy-derive/tests/ui-nightly/derive_transparent.stderr
zerocopy-derive/tests/ui-nightly/enum.stderr
zerocopy-derive/tests/ui-nightly/late_compile_pass.stderr
zerocopy-derive/tests/ui-stable/derive_transparent.stderr
zerocopy-derive/tests/ui-stable/enum.stderr
zerocopy-derive/tests/ui-stable/late_compile_pass.stderr

Previously, some UI tests had missing imports which caused the corresponding `.stderr` files to be populated with unhelpful "cannot find ..." messages. This is another point in favor of #187 (switching to the `ui-test` crate), which presumably would have made it much less likely for this to slip under the radar.

[tests] Fix UI tests with missing imports

---

.github/workflows/ci.yml

Potentially a new per-PR job could be added to CI without it being included in `all-jobs-succeed`'s dependencies.  This prevents that.
I have successfully constructed a [failure](https://github.com/tommy-gilligan/zerocopy/actions/runs/7195624547/job/19598647853) (by deleting a job from `all-jobs-succeed`'s dependencies)
Closes #444

[ci] check all-jobs-succeed depends on all jobs

---

Cargo.toml
src/lib.rs
src/post_monomorphization_compile_fail_tests.rs
zerocopy-derive/Cargo.toml

Ref unsoundness fix 0.7

---

Cargo.toml
src/lib.rs
src/post_monomorphization_compile_fail_tests.rs
zerocopy-derive/Cargo.toml

This commit implements the fix for #716 which will be released as a new version in version trains 0.2, 0.3, 0.4, 0.5, 0.6, and 0.7. See #716 for a description of the soundness hole and an explanation of why this fix is chosen.
Unfortunately, due to dtolnay/trybuild#241, there is no way for us to write a UI test that will detect a failure post-monomorphization, which is when the code implemented in this change is designed to fail. I have manually verified that unsound uses of these APIs now fail to compile.
Release 0.6.6.

Fix soundness hole in Ref::into_ref and into_mut (#721)

---

zerocopy-derive/Cargo.toml

Exclude the following files from the crate file uploaded to crates.io; they are excessively large, and cause the resulting crate file to be large as well.
- tests/enum_from_bytes.rs
- tests/ui-nightly/enum_from_bytes_u16_too_few.rs.disabled
This commit saves a significant amount of space from the published crate file as reported by `cargo package`:
Uncompressed   Compressed
Before     3.6MiB         526.8KiB
After      249.9KiB       41.8KiB
This represents a 14x size reduction uncompressed and a 13x size reduction compressed.
Makes progress on #742

[derive] Exclude large test files when publishing

---

.github/workflows/ci.yml

As reported in obi1kenobi/cargo-semver-checks-action#61, a recent update to the nightly toolchain broke cargo-semver-checks. Previously, we were using the latest nightly toolchain rather than the pinned nightly toolchain in order to run cargo-semver-checks, which caused our CI to break when this new nightly was released.
In this commit, we use our pinned nightly version instead, hopefully avoiding issues like this in the future.

[ci] Use pinned nightly for cargo-semver-checks

---

src/lib.rs

Fixes: 4433ad371114 ("[doc] Use `doc(cfg(...))` in docs.rs (#579)")

[doc] fix doc_cfg feature name of new_vec_zeroed

---

testutil/Cargo.toml

Version 0.1.6 requires a Rust version more recent than our MSRV. To work around this, we take an explicit dependency on it, and pin to 0.1.5.

Pin transitive dep `cargo-platform` for MSRV

---

Cargo.toml
README.md
src/byteorder.rs
src/lib.rs
zerocopy-derive/Cargo.toml

Remove the `byteorder` feature and the dependency on the `byteorder` crate. Replace the `ByteOrder` trait and types which implement it from the `byteorder` crate with our own native implementations. This allows us to make some of our functions and methods `const`.
Add `Usize` and `Isize` byte order-aware types.
Closes #438

[byteorder] Remove byteorder feature and crate dep

---

zerocopy-derive/src/lib.rs
zerocopy-derive/tests/struct_try_from_bytes.rs

Now that #715 supports unaligned `Ptr`s, we get support for `repr(packed)` 'for free' — this commit merely removes the anti-`packed` check from the derive.
Makes progress towards #5.

Support `derive(TryFromBytes)` on `packed` structs.

---

src/pointer/ptr.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/tests/struct_try_from_bytes.rs
zerocopy-derive/tests/union_try_from_bytes.rs

The implementation itself is very straightforward, but it requires a few prerequisite changes:
- The `Ptr::project` method now requires that it only be called on struct and union types
- The `AsInitialized` invariant property is changed in a subtle but important way. Previously, a byte offset in a type was required to be initialized if, in every instance of that type, it was initialized. Now, this is required if the byte is initialized in /any/ instance of the type. Without this change, it would be possible to invoke `TryFromBytes::is_bit_valid` on a byte sequence where an uninitialized byte appears which is valid for one union field but not valid for another. Since we check bit validity for all union fields, uninitialized bytes may only appear which are compatible with /all/ union …

[derive] Derive TryFromBytes on unions

---

zerocopy-derive/src/lib.rs
zerocopy-derive/tests/enum_from_zeros.rs
zerocopy-derive/tests/ui-msrv/enum.stderr
zerocopy-derive/tests/ui-nightly/enum.stderr
zerocopy-derive/tests/ui-stable/enum.stderr

Previously, these were supported, but probably technically shouldn't have been. While in practice unit-only enums have a layout which matches their discriminants, this isn't technically guaranteed without an explicit repr attribute.

[derive] FromZeros requires repr on unit-only enums

---

zerocopy-derive/src/ext.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/tests/ui-msrv/enum.stderr
zerocopy-derive/tests/ui-nightly/enum.stderr
zerocopy-derive/tests/ui-stable/enum.stderr

The implementation of this method checks for the presence of fields. While this is /similar/ to the concept of a C-like enum, it's not the same. Fieldless enums are exactly as described: none of their variants has fields. C-like enums, on the other hand, are more recently referred to as "unit-only" because their variants are not permitted to contain parentheses or curly braces. E.g., the following is a fieldless enum, but is not a C-like/unit-only enum:
```rust
#[repr(u8)]
enum Foo {
A,   // This is fine
B(), // This is not fine
C{}  // This is not fine
}
```
This distinction is important specifically when it comes to discriminants. The syntax `Foo::A as u8` computes the discriminant value of the `A` variant. However, `Foo::B` is a type constructor, and thus is a function. As a result, …

[derive] Rename is_c_like -> is_fieldless

---

src/lib.rs
src/pointer/ptr.rs
src/util.rs

Add TryFromBytes::try_read_from

---

zerocopy-derive/src/lib.rs
zerocopy-derive/tests/enum_try_from_bytes.rs
zerocopy-derive/tests/ui-msrv/enum.stderr
zerocopy-derive/tests/ui-nightly/enum.rs
zerocopy-derive/tests/ui-nightly/enum.stderr
zerocopy-derive/tests/ui-stable/enum.stderr

[derive] TryFromBytes on repr(C) enums

---

.github/workflows/ci.yml
Cargo.toml
cargo.sh

MWRV stands for "minimum working Rust version" (a term we invent here). It is the minimum version of the toolchain that we test with in CI. We maintain (and test) the invariant that MSRV >= MWRV so that we know at all times that our code is compatible with our published MSRV.
The reason for doing this is so that we can make progress towards lowering our MSRV without painting ourselves into a corner. We treat MSRV bumps as breaking changes, so if we were to publish a particular MSRV and then later discover a problem, we wouldn't be able to revert to a previously-published, higher MSRV. By tracking MWRV separately, we can ensure that we're making progress while still leaving ourselves wiggle room to revert changes so long as those reversions are compatible with our published MSRV. Once we …

[ci] Separately track MSRV and MWRV

---

.github/workflows/ci.yml
Cargo.toml
cargo.sh

Reverts google/zerocopy#810
It turns out that while #810 was itself fine, building on it is currently impossible. In particular, when we lower the MWRV to lower than the MSRV, Cargo invocations in CI complain because we're asking it to compile using a toolchain lower than the documented MSRV. This can be bypassed using `--ignore-rust-version`. However, there's no way to instruct the `trybuild` crate (which runs our UI tests) to pass that flag when it invokes Cargo, and so the UI tests fail without recourse.

Revert "[ci] Separately track MSRV and MWRV"

---

src/util.rs

Description says it all. The implementation has detailed comments. Happy to edit commit messages as needed.

Add implementation of `padding_needed_for`

---

Cargo.toml
src/lib.rs
tests/ui-nightly/invalid-impls/invalid-impls.stderr
zerocopy-derive/tests/ui-nightly/derive_transparent.stderr
zerocopy-derive/tests/ui-nightly/late_compile_pass.stderr
zerocopy-derive/tests/ui-nightly/mid_compile_pass.stderr
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-nightly/union.stderr

Add explicit `allow`s to work around Clippy false positive: https://github.com/rust-lang/rust-clippy/issues/12154

Roll nightly toolchain

---

.github/workflows/ci.yml
Cargo.toml
build.rs
src/byteorder.rs
src/macros.rs

For methods which have generic types with trait bounds (other than `Sized`), conditionally compile as `const` only on Rust 1.61.0 or later.

[byteorder] Make some methods const

---

src/lib.rs
src/macros.rs
src/pointer/mod.rs
src/pointer/ptr.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/tests/struct_try_from_bytes.rs
zerocopy-derive/tests/union_try_from_bytes.rs

This opens the door to implementing `TryFromBytes<Option<&T>>`, which is currently blocked on us needing to inspect whether the referent bytes are zeroed. We couldn't do that previously, since `AsInitialized` leaves the possibility for uninitialized bytes, which cannot be soundly checked for equality; described here: https://github.com/rust-lang/unsafe-code-guidelines/issues/488.

Introduce `invariant::Initialized` and migrate `Maybe` to it

---

testutil/Cargo.toml

This will make it marginally easier to lower our MSRV to 1.55 in the future.

[testutil] Downgrade to edition 2018

---

.github/workflows/ci.yml
Cargo.toml
src/lib.rs
src/macros.rs
src/util.rs
src/wrappers.rs
tests/ui-msrv/invalid-impls/invalid-impls.stderr
tests/ui-msrv/transmute-mut-dst-not-intobytes.stderr
tests/ui-msrv/transmute-mut-src-dst-unsized.stderr
tests/ui-msrv/transmute-mut-src-not-frombytes.stderr
tests/ui-msrv/transmute-mut-src-not-intobytes.stderr
tests/ui-msrv/transmute-mut-src-not-nocell.stderr
tests/ui-msrv/transmute-mut-src-unsized.stderr
tests/ui-msrv/transmute-ptr-to-usize.stderr
tests/ui-msrv/transmute-ref-src-dst-unsized.stderr
tests/ui-msrv/transmute-ref-src-not-intobytes.stderr
tests/ui-msrv/transmute-ref-src-not-nocell.stderr
tests/ui-msrv/transmute-ref-src-unsized.stderr
tests/ui-msrv/transmute-src-not-intobytes.stderr
zerocopy-derive/Cargo.toml
zerocopy-derive/tests/ui-msrv/derive_transparent.stderr
zerocopy-derive/tests/ui-msrv/late_compile_pass.stderr
zerocopy-derive/tests/ui-msrv/mid_compile_pass.stderr

Lower MSRV to 1.56

---

src/byteorder.rs
src/lib.rs

Closes #253 
I saw this in the nice-to-haves in #671, so I thought I would knock it out.

Renamed `as_bytes_mut` to `as_mut_bytes`

---

zerocopy-derive/src/lib.rs

Generalize `require_self_sized` to require other `Trait`s.

derive: generalize `require_self_sized`

---

src/lib.rs

TryFromBytes for MaybeUninit<T> requires T: NoCell

---

src/lib.rs
src/pointer/ptr.rs
zerocopy-derive/tests/struct_try_from_bytes.rs
zerocopy-derive/tests/union_try_from_bytes.rs

With the addition of `Initialized`, validity is no longer totally ordered.

Remove unsound `Ptr::forget_valid`

---

src/lib.rs
src/macros.rs
src/pointer/mod.rs
src/pointer/ptr.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/tests/enum_try_from_bytes.rs
zerocopy-derive/tests/struct_try_from_bytes.rs
zerocopy-derive/tests/union_try_from_bytes.rs

[`TryFromBytes`] Permit `UnsafeCells`

---

src/pointer/ptr.rs

[ptr] Clean up prose for field invariants

---

src/lib.rs
src/pointer/mod.rs
src/pointer/ptr.rs

Add TryFromBytes::try_from_mut

---

src/lib.rs
src/macros.rs
src/wrappers.rs

This replaces the implicit implementation, which accepted all values as bit-valid, which was unsound.
While we're here, add more test cases to `test_impls` to test hand-rolled `is_bit_valid` impls for other types.
Closes #897

Implement `<Unalign as TryFromBytes>::is_bit_valid`

---

src/lib.rs
src/macros.rs

Implement TryFromBytes for Option<F> for fn types

---

.github/workflows/ci.yml

[ci] Test Git hooks

---

src/lib.rs

Previously, our test harness for `TryFromBytes` types assumed that those types also implemented `NoCell`. This commit introduces machinery that allows us to conditionally execute certain steps of our tests depending on whether or not the type under test implements `NoCell`.
This commit also lifts the `T: NoCell` bound in `TryFromBytes for MaybeUninit<T>` in order to test this machinery.

Support testing TryFromBytes for !NoCell types

---

src/byteorder.rs
src/lib.rs
src/util.rs
src/wrappers.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/tests/enum_from_bytes.rs
zerocopy-derive/tests/hygiene.rs
zerocopy-derive/tests/include.rs
zerocopy-derive/tests/paths_and_modules.rs
zerocopy-derive/tests/struct_from_bytes.rs
zerocopy-derive/tests/struct_try_from_bytes.rs
zerocopy-derive/tests/union_from_bytes.rs
zerocopy-derive/tests/union_from_zeros.rs
zerocopy-derive/tests/union_try_from_bytes.rs

`#[derive(FromBytes)]` implies `#[derive(FromZeros)]`, which implies `#[derive(TryFromBytes)]`.
Closes #925

[derive] Automatically derive super-traits

---

.github/workflows/ci.yml
.github/workflows/roll-pinned-toolchain-versions.yml

[ci] Automatically roll pinned Kani version

---

.github/workflows/ci.yml

In the shell script that is the main body of the `generate_cache` job, background each task and then wait for them all to complete so that they can run in parallel.

[ci][generate_cache] Run steps in parallel

---

zerocopy-derive/src/lib.rs

This makes the transition from `AsBytes` to `IntoBytes` (its new name) easier.
Makes progress on #695

[derive] Support deriving deprecated AsBytes

---

ci/check_all_toolchains_tested.sh
ci/check_msrv.sh
ci/check_readme.sh
ci/check_versions.sh
githooks/pre-push

While we're here, add `-q` flags to all `cargo` invocations in scripts in the `ci` directory.

[githooks][pre-push] Run steps in parallel

---

src/lib.rs

This allows the callback passed to `with_passing_test_cases` to access its argument mutably. We don't make use of this ability in this commit, but it will become important later when we implement `TryFromBytes` for `UnsafeCell`.
Makes progress on #5

Use Box instead of &T in test_impls success cases

---

src/pointer/ptr.rs

Make Ptr::reborrow public

---

src/lib.rs

Fix some uses of FromBytes and NoCell in doc tests

---

tests/trybuild.rs
tests/ui-msrv/invalid-impls/invalid-impls.stderr
tests/ui-msrv/transmute-mut-dst-not-intobytes.stderr
tests/ui-msrv/transmute-mut-src-not-intobytes.stderr
tests/ui-msrv/transmute-ptr-to-usize.stderr
tests/ui-nightly/invalid-impls/invalid-impls.rs
tests/ui-nightly/invalid-impls/invalid-impls.stderr
tests/ui-nightly/transmute-mut-dst-not-frombytes.rs
tests/ui-nightly/transmute-mut-dst-not-intobytes.rs
tests/ui-nightly/transmute-mut-dst-not-nocell.rs
tests/ui-nightly/transmute-mut-src-not-frombytes.rs
tests/ui-nightly/transmute-mut-src-not-intobytes.rs
tests/ui-nightly/transmute-mut-src-not-nocell.rs
tests/ui-nightly/transmute-ref-dst-not-nocell.rs
tests/ui-stable/invalid-impls/invalid-impls.stderr

While we're here, add an `assert!` that prevents us from running UI tests when the `derive` feature is disabled. The `derive` feature is required in order for UI tests to produce sensible output, and running without it enabled is a common source of mis-steps when developing that ends up slowing us down.

Fix UI tests

---

zerocopy-derive/tests/ui-msrv/derive_transparent.stderr
zerocopy-derive/tests/ui-msrv/enum.stderr
zerocopy-derive/tests/ui-msrv/late_compile_pass.stderr
zerocopy-derive/tests/ui-nightly/derive_transparent.rs
zerocopy-derive/tests/ui-nightly/derive_transparent.stderr
zerocopy-derive/tests/ui-nightly/enum.rs
zerocopy-derive/tests/ui-nightly/enum.stderr
zerocopy-derive/tests/ui-nightly/late_compile_pass.stderr
zerocopy-derive/tests/ui-stable/derive_transparent.stderr
zerocopy-derive/tests/ui-stable/enum.stderr
zerocopy-derive/tests/ui-stable/late_compile_pass.stderr

[derive] Fix UI tests

---

src/lib.rs

Fix some uses of NoCell in doc tests

---

src/lib.rs
src/pointer/ptr.rs

Fix Clippy lints

---

cargo.sh
src/lib.rs
src/macros.rs
tests/ui-msrv/transmute-mut-dst-not-intobytes.stderr
tests/ui-msrv/transmute-mut-src-not-intobytes.stderr
tests/ui-msrv/transmute-ptr-to-usize.stderr
tools/cargo-zerocopy/src/main.rs
zerocopy-derive/tests/ui-msrv/derive_transparent.stderr
zerocopy-derive/tests/ui-msrv/late_compile_pass.stderr

[cargo-zerocopy] Pass failure return codes through

---

src/byteorder.rs

All numeric types can implement `PartialOrd` and `Ord`, except floats, which can only implement `PartialOrd`.
We cannot simply implement `PartialOrd` via `@all_types` because then clippy will complain about `PartialOrd` not being implemented in terms of `Ord` (see [`clippy::non_canonical_partial_ord_impl`](https://rust-lang.github.io/rust-clippy/master/index.html#/non_canonical_partial_ord_impl) lint) for non-floats.

Implement `PartialOrd` and `Ord` where possible

---

src/lib.rs
tests/ui-msrv/invalid-impls/invalid-impls.stderr
tests/ui-msrv/transmute-ptr-to-usize.stderr
tests/ui-msrv/transmute-ref-src-not-intobytes.stderr
tests/ui-msrv/transmute-src-not-intobytes.stderr
tests/ui-nightly/invalid-impls/invalid-impls.stderr
tests/ui-nightly/transmute-mut-dst-not-intobytes.stderr
tests/ui-nightly/transmute-mut-src-not-intobytes.stderr
tests/ui-nightly/transmute-ptr-to-usize.stderr
tests/ui-nightly/transmute-ref-src-not-intobytes.stderr
tests/ui-nightly/transmute-src-not-intobytes.stderr
tests/ui-stable/invalid-impls/invalid-impls.stderr
tests/ui-stable/transmute-mut-dst-not-intobytes.stderr
tests/ui-stable/transmute-mut-src-not-intobytes.stderr
tests/ui-stable/transmute-ptr-to-usize.stderr
tests/ui-stable/transmute-ref-src-not-intobytes.stderr
tests/ui-stable/transmute-src-not-intobytes.stderr
tools/cargo-zerocopy/src/main.rs
zerocopy-derive/tests/enum_try_from_bytes.rs
zerocopy-derive/tests/ui-msrv/derive_transparent.stderr
zerocopy-derive/tests/ui-msrv/late_compile_pass.stderr
zerocopy-derive/tests/ui-nightly/derive_transparent.stderr
zerocopy-derive/tests/ui-nightly/late_compile_pass.stderr
zerocopy-derive/tests/ui-stable/derive_transparent.stderr
zerocopy-derive/tests/ui-stable/late_compile_pass.stderr

See #960 for an explanation of why we do this.
Closes #960

Disable re-exporting renamed traits in dev and CI

---

src/lib.rs
src/pointer/mod.rs
src/pointer/ptr.rs
src/util.rs
zerocopy-derive/src/lib.rs

[ptr] Add TransparentWrapper

---

src/lib.rs
src/pointer/ptr.rs

Add `IntoByteSlice` and `IntoByteSliceMut` traits, which extend `ByteSlice` and `ByteSliceMut`, adding `Into<&[u8]>` and `Into<&mut [u8]>` bounds respectively. Use these new traits as the bounds in the `Ref` methods `into_ref`, `into_mut`, `into_slice`, and `into_mut_slice`. This allows us to remove the post-monomorphization error which was originally added to patch the soundness hole in #716 in a backwards-compatible way.
Closes #758

Add `IntoByteSlice` trait, use as bound for `into_ref`

---

githooks/pre-push

Previously, the script didn't properly detect when a backgrounded sub-command had failed, and unconditionally exited with status code 0. This commit fixes that behavior so that, if a sub-command fails, the script exits with a non-zero status code.

[githooks/pre-push] Fail when sub-command fails

---

README.md
src/lib.rs

Document `TryFromBytes`

---

Cargo.toml
src/pointer/ptr.rs

[ci] Roll pinned nightly toolchain

---

src/lib.rs
zerocopy-derive/src/lib.rs

Make TryFromBytes a super-trait of FromZeros

---

src/lib.rs

`FromBytes::ref_from` now supports slices, and is strictly more powerful.

Deprecate FromBytes::slice_from

---

src/lib.rs

Previously, we re-exported renamed traits as their old names via `pub use`. Despite including `#[deprecated]` attributes on each `pub use`, it still caused problems for us as described in #960.
In this commit, we replace `pub use` with just `use`. This has the effect of making it so that using the old names is an error rather than a warning, which accomplishes two things: first, it ensures that the issue described in #960 can't happen, as the compiler will never generate suggestions to write code which generates errors. Second, it ensures that callers are forced to update to the new names, which makes it less likely for us to cause breakage when we eventually remove the `use` path.
Note that, despite no longer having an explicit deprecation warning that explains what's happening, the …

Make old names errors instead of warnings

---

src/lib.rs

Document `Unaligned`

---

src/lib.rs

This was renamed to `as_mut_bytes` in #870. This commit adds the old name back as a `#[doc(hidden)]`, `#[deprecated]` alias to ease the transition.
Closes #986

Add deprecated IntoBytes::as_bytes_mut

---

.github/workflows/roll-pinned-toolchain-versions.yml
src/lib.rs
tools/cargo-zerocopy/src/main.rs

This commit builds on #980 in a few ways:
- Consolodates `use` lines so we can avoid repeating the same comment multiple times.
- Applies the same technique to the old `LayoutVerified` name (for what is now called `Ref`)
- In #980, we spuriously left `IntoBytes as AsBytes` as a `pub use` rather than just a `use`, which caused us to need to keep the `--cfg __INTERNAL_USE_ONLY_DISABLE_DEPRECATED_TRAIT_ALIASES` in order to keep CI passing. We fix that in this commit, and thus can remove that `--cfg`.

Consolodate and improve use of old names

---

src/lib.rs

Implement Copy and Clone for Ref

---

src/lib.rs

Documents the derive, and aligns the trait documentation with that of other traits.

Document `KnownLayout`

---

src/byteorder.rs
src/lib.rs

Split ByteSlice and SplitByteSlice

---

README.md
src/lib.rs

In #983 we utilized H6 level headers is our overview documentation. Unfortunately, the readme generator up-levels all headers by one degree, and there's no such thing as an H7.
Closes #998

Delevel headers in crate-level documentation

---

src/byteorder.rs
src/lib.rs
src/macro_util.rs
src/pointer/mod.rs
src/pointer/ptr.rs
tests/ui-nightly/transmute-mut-dst-not-a-reference.stderr
tests/ui-nightly/transmute-ref-dst-mutable.stderr
tests/ui-nightly/transmute-ref-dst-not-a-reference.stderr
tests/ui-nightly/transmute-ref-src-dst-not-references.stderr
tests/ui-stable/transmute-mut-dst-not-a-reference.stderr
tests/ui-stable/transmute-ref-dst-mutable.stderr
tests/ui-stable/transmute-ref-dst-not-a-reference.stderr
tests/ui-stable/transmute-ref-src-dst-not-references.stderr

Add Clippy lints to help prevent regressions.
Closes #188

Annotate public macros/functions with `#[must_use]`

---

src/lib.rs

These became redundant at some point in the past, but didn't cause any compilation issues, so we didn't notice.

Remove unnecessary Ptr "assume" calls

---

src/pointer/ptr.rs
src/util.rs
src/wrappers.rs

[wrappers] Replace some `unsafe` code with `Ptr`

---

src/lib.rs

Document const-ness of `transmute(_*)!` macros

---

src/macros.rs
src/pointer/ptr.rs
src/util.rs

This will allow us to implement `TransparentWrapper` for `T` where `T` and `T::Inner` do not have `UnsafeCell`s at the same byte ranges. This, in turn, will let us automatically implement traits for these types so long as those traits don't require reasoning about `UnsafeCell` ranges (in other words, all traits other than `NoCell`).

TransparentWrapper supports UnsafeCell variance

---

src/lib.rs
src/macros.rs
src/pointer/ptr.rs
src/util.rs

This allows us to replace unsafe implementations of core traits with
safe ones, using the `TransparentWrapper` bound to prove safety via the
`impl_for_transparent_wrapper!` macro.

Implement `TransparentWrapper` for `UnsafeCell`

---

src/deprecated.rs
src/lib.rs

Move deprecated items to dedicated module

---

src/lib.rs

To my eyes, this is much more easily comprehensible at a glance than the prosaic alternative.
If this looks good to you, @joshlf, I'll apply the pattern to `transmute!` and `transmute_mut!` too. 
Partially addresses #1046.

Use pseudocode to document `transmute_ref`

---

src/lib.rs

Use pseudocode to document `transmute`, `transmute_mut`

---

zerocopy-derive/Cargo.toml

This is a temporary work-around for #1085. Per #1088, we will remove this and implement a more complete fix before releasing 0.8 (#671).

[derive] Pin syn to 2.0.55

---

.github/workflows/ci.yml

This is intended to fix https://github.com/model-checking/kani/issues/3138

[ci] Roll Kani to 0.50.50

---

src/lib.rs

Given the importance of avoiding panic paths to some of our customers, we should, as a rule, avoid only offering (or relying upon) APIs with panic paths.
Related to #202

Add `SplitByteSlice::split_at_unchecked`

---

src/lib.rs
zerocopy-derive/tests/struct_try_from_bytes.rs

For example, `try_from_ref` is now `try_ref_from`.
See: https://github.com/google/zerocopy/discussions/1095

Rename `TryFromBytes` methods to be consistent with `FromBytes`

---

src/lib.rs

This change makes the slice and non-slice conversion methods consistent, and provides a lightweight way (i.e., without `Ref`) to access the leftover bytes after conversions. For instance, this:
```rust
trait FromBytes {
fn ref_from_prefix(bytes: &[u8]) -> Option<&Self>
where
Self: KnownLayout + NoCell;
}
```
...becomes this, in this PR:
```rust
trait FromBytes {
fn ref_from_prefix(bytes: &[u8]) -> Option<(&Self, &[u8])>
where
Self: KnownLayout + NoCell;
}
```
...where the second element of the tuple are the remaining bytes. Providing the remainder eases the pattern where a `T` is parsed from a buffer, and then the buffer is advanced to exclude the parsed `T`.
This PR tests out the 'feel' of tuple-returning conversion methods. Alternatively, we could provide a mirror set of `_split` …

Also return remaining bytes in `FromBytes` conversion methods

---

src/lib.rs
src/macros.rs
src/pointer/ptr.rs
zerocopy-derive/src/lib.rs

Makes progress on https://github.com/google/zerocopy/issues/29

KnownLayout tracks pointer metadata type

---

src/deprecated.rs
src/lib.rs

Add `Ref` constructors which are generic over `T:
KnownLayout<PointerMetadata = usize>` - in other words, types whose trailing field is a slice (i.e., slices or slice DSTs). These constructors take an explicit element count for the trailing slice, and replace the previous constructors which only supported slices.

Add non-slice Ref constructors w/ slice elem count

---

src/lib.rs

This enables Clippy's [`expect_used`](https://rust-lang.github.io/rust-clippy/master/index.html#/expect_used) lint, which errors on calls to `Option::expect` and `Result::{expect, expect_err}`. The intent of enabling this lint is to reduce the number of panics emitted in `zerocopy`'s code (issue #202).

Replace a panic with an error branch

---

src/lib.rs
src/pointer/ptr.rs
src/util.rs

Presently, we deny ZSTy DSTs in our APIs via panicking at runtime. However, the ZSTiness of a DST is statically detectable and can be denied instead at compile time. This PR replaces our ZSTy DST panics with compile-time assertions. Doing gives us the freedom later provide meaningful runtime semantics in such cases.
Partially addresses https://github.com/google/zerocopy/issues/325
Closes https://github.com/google/zerocopy/issues/1149

Use compile-time assertions to deny ZSTy DSTs

---

src/lib.rs
src/macros.rs
src/pointer/mod.rs
src/pointer/ptr.rs
zerocopy-derive/src/lib.rs

This replaces `at_least::Xxx` with `AtLeast<Xxx>`, which in turn allows us to write `AtLeast<T>` in a context where `T` is generic.
The use case in this commit is to relax the bound on `Copy` and `Clone` to:
Shared: AtLeast<I::Aliasing>
...which is equivalent to saying that `I::Aliasing` is at *most* `Shared`. This permits both `Shared` and `Any` `Ptr`s to be copied or cloned.

[pointer] Make "at least" machinery generic

---

.github/workflows/release-crate-version.yml

This can be triggered manually via the GitHub web UI, and will generate a PR which updates the crate versions in both `Cargo.toml` files.

Add "release new crate version" workflow

---

src/lib.rs
src/macros.rs
src/pointer/mod.rs
src/pointer/ptr.rs
zerocopy-derive/src/lib.rs

[pointer] Support as_bytes on unsized types

---

src/byteorder.rs
src/deprecated.rs
src/error.rs
src/layout.rs
src/lib.rs
src/pointer/ptr.rs
zerocopy-derive/tests/enum_try_from_bytes.rs
zerocopy-derive/tests/struct_try_from_bytes.rs

This is an implementation of the ideas presented in #1139.
This PR:
1. introduces the public `error` module (whose items are also re-exported)
2. revises zerocopy's APIs to return `Result`s with informative error types, rather than `Option`s
Generally speaking, zerocopy’s conversions may fail for one of up to three reasons, each reflected in a fundamental error type:
-  `AlignmentError<Src, Dst>`: the conversion source was improperly aligned
- `SizeError<Src, Dst>`: the conversion source was of incorrect size
- `ValidityError<Src, Dst>`: the conversion source contained invalid data
These fundamental error types are parameterized with the failed conversion's:
- `Src`: the input value of the conversion, stored within the error; and
- `Dst`: the output type of the conversion, retained as …

Overhaul error reporting (enum version)

---

.github/workflows/ci.yml

This backports the existing behavior from `main` so we can  auto-roll Kani on the `0.7.x` branch.

[ci] Pin Kani version

---

.github/workflows/roll-pinned-toolchain-versions.yml

In a previous commit (#1190 / a49e91c), we introduced the `${{ matrix.branch }}` variable, but only one job in the file already had a "matrix" strategy. `roll_kani` did not, and so that variable is always empty.

Fix bug in Kani roller

---

src/pointer/ptr.rs
src/wrappers.rs

This make's `Unalign`'s methods consistent with zerocopy's other methods, and, in the case of `Unalign::try_deref_mut`, allows the original `&mut Unalign<T>` to be reused in the event of failure.
Makes progress towards #1139

Use `AlignmentError` in `Unalign`'s failure conditions

---

build.rs
src/lib.rs

[`build.rs`] Support `unexpected_cfgs` lint

---

zerocopy-derive/tests/struct_to_bytes.rs

In #1182, a failure was reported for `AsBytes` (now renamed to `IntoBytes`). We haven't yet been able to reproduce this failure, but this commit adds that failure case verbatim so that we don't regress in the future.

[derive][tests] Test IntoBytes failure #1182

---

src/lib.rs

Add `ref_` prefix to `from_{prefix,suffix}_with_trailing_elements` to be consistent with other methods.
Makes progress on #871

[FromBytes] Rename some methods for consistency

---

src/lib.rs
src/ref.rs

This allows us to more strictly enforce the requirement that, for `Ref`'s `ByteSlice` field, methods are never called other than those defined on the `ByteSlice`, `ByteSliceMut`, `IntoByteSlice`, and `IntoByteSliceMut` traits. We accomplish this by keeping the field private, and only exposing unsafe getters which return, for example, `&impl ByteSlice`.
We also introduce new traits - `CopyableByteSlice` and `CloneableByteSlice`. We tighten the `Copy` and `Clone` impls for `Ref` to require these bounds. Previously, `ByteSlice` required that its "dereference stability" requirement applied to any `Copy` or `Clone` impls, but this would have prevented us from implementing `ByteSlice` for `Vec`. By splitting the requirement into separate traits, we open the door to supporting `Vec` (#992).

[ref] Move `Ref` definition into its own module

---

src/lib.rs
src/macros.rs
src/pointer/ptr.rs
src/util.rs
src/wrappers.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/tests/struct_try_from_bytes.rs
zerocopy-derive/tests/union_try_from_bytes.rs

TODO:
- Update `project`
- More verbose commit message

[pointer] Relax UnsafeCell requirements

---

src/lib.rs
src/pointer/aliasing_safety.rs
src/pointer/mod.rs
src/pointer/ptr.rs
src/ref.rs

This commit adds the `pointer::aliasing_safety::AliasingSafe` trait, which is implemented for pointer conversions which do not violate aliasing. This can happen either because the aliasing is exclusive or because neither type contains `UnsafeCell`s.
This paves the way for us to remove `Immutable` bounds from some of our API, including from some derives.
Makes progress on #251

Add `AliasingSafe` framework

---

.github/workflows/docs.yml

[ci] Publish `cargo doc` to GitHub Pages

---

src/lib.rs
src/pointer/ptr.rs
src/ref.rs

Ptr::try_cast_into takes explicit element count 

---

src/lib.rs

Implement `FromBytes::{mut,ref}_from_with_trailing_elements`

---

src/deprecated.rs

This commit makes some progress, but more remain to be added.
Makes progress on #871

Add back some removed `Ref` methods as deprecated

---

src/impls.rs
src/pointer/ptr.rs

This causes methods like `TryFromBytes::try_mut_from` to fail compilation during post-monomorphization when used with types containing `UnsafeCell`s. This wasn't caught because our tests hadn't been updated to exercise this condition. This commit also updates the tests so this can't slip through in the future.

Remove .forget_exclusive from Ptr::try_into_valid

---

src/deprecated.rs
src/ref.rs

While we're here, rename `from` to `from_bytes` so that naming is consistent (otherwise, we'd have to add `from_with_elems` rather than `from_bytes_with_elems`, which is a weird name).

Add Ref more `with_elems` `Ref` constructors

---

src/lib.rs

We do support deriving `TryFromBytes` on unions, and our conservative assumptions of their validity generally match intuition.
Makes progress towards #5.

Remove incorrect `TryFromBytes` docs w.r.t unions

---

src/lib.rs

It has safety invariants, so it should have been unsafe all along.

Make `IntoByteSlice` an unsafe trait

---

src/lib.rs
src/macro_util.rs
src/macros.rs
src/ref.rs
src/util.rs

By asserting in a macro, rather than a helper function, rustc's diagnostics point to the user's callsite, rather than our own.

Improve UI/UX of post-monomorphization errors

---

.gitignore
build.rs
src/lib.rs
src/macro_util.rs
src/macros.rs
src/ref.rs
src/util.rs
src/wrappers.rs
tests/ui-nightly/transmute-mut-src-dst-unsized.stderr
tests/ui-nightly/transmute-mut-src-unsized.stderr
tests/ui-nightly/transmute-ref-src-dst-unsized.stderr
tests/ui-nightly/transmute-ref-src-unsized.stderr
tests/ui-stable/transmute-mut-src-dst-unsized.stderr
tests/ui-stable/transmute-mut-src-unsized.stderr
tests/ui-stable/transmute-ref-src-dst-unsized.stderr
tests/ui-stable/transmute-ref-src-unsized.stderr

Add tests for some uncovered lines

---

src/deprecated.rs
src/lib.rs

- Rename some non-deprecated `FromBytes` methods:
- `mut_from` -> `mut_from_bytes`
- `mut_from_with_elems` -> `mut_from_bytes_with_elems`
- `read_from` -> `read_from_bytes`
- Add missing deprecated `Ref` methods:
- `new_unaligned`
- `new_unaligned_from_prefix`
- `new_unaligned_from_suffix`
- In `FromBytes`, coalesce deprecated methods at the end of the trait
- Update names in deprecation messages (some names were stale)
- Make all deprecated methods return `Option`s rather than `Result`s, consistent with their equivalents on 0.7
- Mark all deprecated methods as `#[inline(always)]`
Makes progress on #871

Update deprecated methods for `FromBytes`, `Ref`

---

src/lib.rs

In particular, add tests for `transmute_mut!` and `try_transmute!`.

Expand test_macros_evaluate_args_once to test more

---

src/error.rs

This permits matching on the error variant, and ensures that the variants are rendered in rustdoc.
Makes progress on #1139.

Make `ConvertError` and variants public

---

ci/check_all_toolchains_tested.sh
ci/check_fmt.sh
ci/check_job_dependencies.sh
ci/check_readme.sh
githooks/pre-push

Previously, some scripts had output which would only be generated on failure, but this output was passed to stdout, which `githooks/pre-push` pipes to `/dev/null`. In this commit, any such output is unconditionally redirected to `stderr` - if there's any output, we want to see it. This previously resulted in very opaque errors during `git push`, which should be addressed by this commit.
Also, in #728, we added `ci/check_all_toolchains_tested.sh`, but didn't add it to `githooks/pre-push`. In this commit, we fix that, and also add a test to `githooks/pre-push` to validate that all scripts in `ci/*` at least show up in `githooks/pre-push` by name. This isn't a foolproof check, but it should catch obvious errors.

[githooks] CI scripts pipe failures to stderr

---

src/byte_slice.rs
src/ref.rs

Remove the `Into<&[u8]>` and `Into<&mut [u8]>` bounds on `IntoByteSlice` and `IntoByteSliceMut` and replace them with methods. This allows `IntoByteSlice` to be implemented for `&mut [u8]` (and, as a consequence, permits `Ref::<&mut [u8], _>::into_ref`), which was previously barred.
Closes #1260

Move `IntoByteSlice[Mut]: Into` into methods

---

src/lib.rs
zerocopy-derive/src/lib.rs

Add more safety proof to `KnownLayout` derive

---

.github/workflows/ci.yml

Use `cargo nextest` to run Miri tests on twice the number of threads as there are CPU cores.

[ci] Run Miri tests on multiple threads

---

.github/workflows/ci.yml
src/pointer/ptr.rs

This should enable better parallelization, especially under Miri in CI.

Split `test_ptr_try_cast_into_soundness`

---

.github/workflows/ci.yml

Comparing [1] (run with the parent commit) and [2] (run with this commit), we see an overall speedup of 19m33s -> 6m53s, or ~65%. These gains will only be realized during PR development; the CI test execution time in the merge queue will remain unchanged.
[1] https://github.com/google/zerocopy/actions/runs/9149347472
[2] https://github.com/google/zerocopy/actions/runs/9149505999?pr=1313

[ci] Only run Miri tests in merge queue

---

.github/workflows/ci.yml

Comparing [1] (run with the parent commit) and [2] (run with this commit), we see an overall speedup of 6m54s -> 5m36s, or ~19%. These gains will only be realized during PR development; the CI test execution time in the merge queue will remain unchanged.
Makes progress on https://github.com/google/zerocopy/issues/1310
[1] https://github.com/google/zerocopy/actions/runs/9149561660
[2] https://github.com/google/zerocopy/actions/runs/9149620991?pr=1314

[ci] Test some targets only in the merge queue

---

src/macro_util.rs

This test started failing in a recent nightly toolchain roll under `-Zrandomize-layout`. The problem is that `#[repr(packed)]` does not imply that field ordering in the packed struct remains in lexical order. Switching the layout of the tested struct to `#[repr(C, packed)]` fixes this.
Local repro (WSL):
```
$ RUSTFLAGS="--cfg __INTERNAL_USE_ONLY_NIGHTLY_FEATURES_IN_TESTS -Dwarnings -Zrandomize-layout -Zlayout-seed=1" cargo +nightly-2024-05-30 test --package zerocopy --features __internal_use_only_features_that_work_on_stable -- --skip ui
```
fyi @joshlf

Fix incorrect trailing field offset test

---

.github/actions/cache/action.yml

This fixes the `node.js` deprecation warnings that appear in the CI runs. v4 introduces a bit more noise to the build summary (under Annotations). It can be removed if you don't find them useful (doc [link](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#removing-job-summaries)).
[Test run](https://github.com/sl4m/zerocopy/actions/runs/9388820927) on my fork.

[ci] Updates actions/cache to v4

---

.github/workflows/ci.yml

This commit addresses several issues related to the generation of Rust documentation:
1. Corrects the extraction of `rustdoc-args` from `Cargo.toml`, resolving #1228
2. Transfers `rustdoc` flags that are exclusive to the `nightly` toolchain from `rustdoc-args` in `Cargo.toml` to `RUSTDOCFLAGS`. This ensures that the documentation generation process is aligned  with the correct toolchain environment.
3. Add `set -eo pipefail` in the CI job `Cargo doc` to enhance the robustness of the CI pipeline.

Resolve Flags Handling and Improve CI Stability

---

Cargo.toml
README.md
src/error.rs
src/lib.rs
src/macros.rs
src/util.rs

While we're here, also relax `Dispaly for AlignmentError<Src, Dst>` to permit `Dst: ?Sized` in exchange for `Dst: KnownLayout`. This is an important relaxation since our APIs permit performing conversions into unsized destination types with runtime alignment checking.
Makes progress on #1297

[error] Implement std::error::Error on errors

---

src/lib.rs
src/util.rs

In doing so, we eliminate a potential panic path. Although I was not able to observe panic paths emitted in toy examples, they might be emitted in complex examples in which the optimizer is low on gas. Regardless, I expect this change will ease our future adoption of call-graph analysis techniques of potential panic paths.
Ref https://github.com/google/zerocopy/issues/200#issuecomment-2181544061

Use `copy_nonoverlapping` instead of `slice::copy_from`

---

src/error.rs
src/impls.rs
src/lib.rs
zerocopy-derive/tests/enum_try_from_bytes.rs
zerocopy-derive/tests/struct_try_from_bytes.rs

- `try_mut_from` -> `try_mut_from_bytes`
- `try_read_from` -> `try_read_from_bytes`
- `try_ref_from` -> `try_ref_from_bytes`
Makes progress towards #871

Rename `TryFromBytes` methods for consistency with `FromBytes`

---

src/impls.rs
src/wrappers.rs

We should not use `derive(KnownLayout)` on `Unalign`, because the derive is not smart enough to realize that `Unalign<T>` is always sized and thus emits a `KnownLayout` impl bounded on `T: KnownLayout.` This is overly restrictive.
Fixes #1162

Always use manual impl of `KnownLayout` for `Unalign`

---

.github/workflows/ci.yml
POLICIES.md
zerocopy-derive/Cargo.toml

Relax zerocopy-derive's MSRV policy 

---

build.rs
src/layout.rs
src/lib.rs
src/macro_util.rs
src/util.rs
tools/cargo-zerocopy/src/main.rs

Also renames `__INTERNAL_USE_ONLY_NIGHTLY_FEATURES_IN_TESTS` to `__ZEROCOPY_INTERNAL_USE_ONLY_NIGHTLY_FEATURES_IN_TESTS` for consistency.

Add toolchain cfg for testing msrv

---

.vscode/settings.json
zerocopy-derive/tests/enum_from_bytes.rs

The large enums in zerocopy-derive's `enum_from_bytes` test make rust-analyzer hang during analysis. This change adds a VSCode config that allows us to hide that test from rust-analyzer. The test is still run as normal.
(split out from #879)

Hide large enums from rust-analyzer

---

zerocopy-derive/src/lib.rs
zerocopy-derive/tests/enum_from_zeros.rs
zerocopy-derive/tests/ui-msrv/enum.stderr
zerocopy-derive/tests/ui-nightly/enum.rs
zerocopy-derive/tests/ui-nightly/enum.stderr
zerocopy-derive/tests/ui-stable/enum.stderr

Enums with negative explicit discriminants can allow variants which are not first but have an implicit discriminant to be assigned a discriminant of zero.

Improve zero discriminant detection for enums

---

src/macro_util.rs

Removes previous warning on `trailing_field_offset!` macro.

Fix incorrect trailing field offset test (#1370)

---

.github/workflows/ci.yml
Cargo.toml
tools/Cargo.toml
tools/cargo-zerocopy/Cargo.toml
tools/cargo-zerocopy/src/main.rs

This prevents the lockfile for the workspace from being generated by a newer version of cargo, which may choose more up-to-date dependencies than our msrv toolchain can compile.

Parse the package manifest directly for toolchains

---

src/macro_util.rs

Previously, we needed to rely on the fact that the instance of any valid Rust type with 0 elements has a size (in number of bytes) which is not greater than `isize::MAX`. Providing this as a guarantee turned out to be controversial. [1]
This was made possible by https://github.com/rust-lang/rust/pull/126152.
[1] https://github.com/rust-lang/unsafe-code-guidelines/issues/465#issuecomment-2133405687

Strengthen soundness proof for size_of_val_raw

---

.github/workflows/roll-pinned-toolchain-versions.yml
tools/cargo-zerocopy/src/main.rs

By doing so, we prevent CI from being blocked by our dev-dependencies taking dependencies on earlier versions of zerocopy. Such a scenario introduces multiple packages named "zerocopy" and "zerocopy-derive" into the build, and, consequently, `-p zerocopy` and `-p zerocopy-derive` become ambiguous.

[ci] fully qualify `--package` IDs in toolchain roller

---

.github/workflows/roll-pinned-toolchain-versions.yml

Having a lockfile is a prerequisite of invoking `cargo pkgid`.

[ci] generate lockfile in roller

---

Cargo.toml
src/layout.rs

We can just replace this with assert! and matches!, which are both stable before 1.56.

Remove dependency on assert_matches

---

.github/workflows/ci.yml

This commit modifies our CI `build_test` matrix job to skip some matrix combinations that are unlikely to be useful. This should cut down on the total number of matrix combinations and buy us runway before we exceed the limit of 256 total combinations, as happened in [1].
[1] https://github.com/google/zerocopy/actions/runs/10477927587

[ci] Skip some matrix combinations

---

src/lib.rs

On lower opt-levels the compiler might not optimize out the `layout.size() == 0` branch and emits code for the if-body. This will cause a stack allocation for `Self`. Avoid calling new_zeroed() and directly construct the Box from a dangling pointer instead.

never construct value on stack in new_box_zeroed

---

src/pointer/ptr.rs

Now that [1] is completed, zero-sized accesses no longer require provenance. Per [2], zero-sized references are no longer required to be dereferenceable, and so may not carry provenance.
This commit updates `Ptr`'s invariants to not require provenance or a valid allocation when its referent is zero-sized.
[1] https://github.com/rust-lang/rust/issues/117945
[2] https://github.com/rust-lang/rust/pull/125021
Closes #874

[pointer] Update requirements for zero-sized types

---

src/impls.rs
src/pointer/ptr.rs
src/util.rs

Adds some informal proofs as accepted risks per #1358
Makes progress on #896

Write some safety proofs

---

src/lib.rs

The documentation now mirrors the structure of the zerocopy_derive source code.

Redocument `derive(IntoBytes)` to reflect current implementation

---

src/macro_util.rs
src/wrappers.rs

Tighten soundness of `addr_of!` uses

---

src/deprecated.rs
src/lib.rs
src/ref.rs

Since `Ref` implements `Deref`, methods risk conflicting with methods of the same names on the target type.
Note that, in #210, we considered applying the same change to `Unalign`. We choose not to do that because most uses of `Unalign` involve types with alignments greater than 1, and for these types, `Unalign` does not implement `Deref`. It's not worth making the API significantly more cumbersome in order to make it easier for this niche use case.
Closes #210

[Ref] Make methods into associated functions

---

src/error.rs
src/impls.rs
src/lib.rs

FromZeros boxed slice method supports slice DSTs

---

src/impls.rs
src/pointer/ptr.rs
src/util.rs

Implement TryFromBytes for unsized UnsafeCell

---

src/util.rs

Add safety comment for MaybeUninit UnsafeCell

---

src/lib.rs
zerocopy-derive/src/lib.rs

Document derive requirements for enums

---

src/lib.rs

"C-like" enums reference was changed to "field-like", which was the only reference.
Closes #985

Update document about field-less enums in lib.rs

---

.github/workflows/ci.yml
Cargo.toml
src/layout.rs
src/lib.rs
src/util/macros.rs
src/util/mod.rs

They now return `AllocError` on allocation failure. `insert_vec_zeroed` still panics if its `position` argument is out-of-bounds.
Closes #1653

Make extend_vec_zeroed, insert_vec_zeroed fallible

---

README.md
src/lib.rs

[doc] Update wording regarding transmute macros

---

zerocopy-derive/Cargo.toml
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs

[derive] Test exact output of derives

---

src/lib.rs

Document that writes to padding bytes are not preserved when an object is moved or copied.
Makes progress on #1648

Document that writes to padding are not preserved

---

README.md
src/lib.rs

Clarify advice for how to speed up compile times by importing zerocopy and zerocopy-derive separately. The updated advice avoids the risk of duplicate import errors if one of a crate's transitive dependencies adds zerocopy's `derive` feature.
Closes #1587

[docs] Clarify derive dependency recommendation

---

zerocopy-derive/src/enum.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs

[derive] Test TryFromBytes output on dataful enums

---

README.md
src/lib.rs

[docs] Link to 0.8 release notes

---

zerocopy-derive/src/output_tests.rs

[derive] More complex TryFromBytes enum output tests

---

src/byteorder.rs

This will allow us to add additional supertraits without breaking users.
Makes progress towards #1692

Seal `ByteOrder` trait

---

src/lib.rs
src/util/mod.rs
src/wrappers.rs

[Unalign] Update docs

---

src/byteorder.rs

[byteorder] Clean up docs

---

src/lib.rs

While the ergonomics of calling these as associated functions on `FromZeros` is not as good as the ergonomics of them as bare functions, the discoverability is considerably higher.

Move Vec zero extension functions to FromZeros

---

zerocopy-derive/Cargo.toml
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs

Our previous output tests asserted on the exact token stream, which is sensitive to subtle differences like `> >` vs `>>` in type signatures. With this change, we instead test for string equality *after* performing a pretty-printing pass, which has the effect of normalizing most such differences, thus making our tests more robust and less sensitive to these inconsequential syntax details.

[derive] Make output tests insensitive to syntax

---

src/util/macro_util.rs
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-nightly/struct.rs
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/struct.stderr

Improve IntoBytes derive error message

---

src/lib.rs

`FromBytes::read_from_suffix` should return a `SizeError`, like `read_from_bytes` and `read_from_prefix`. This commit corrects this error, and also removes unreachable panic paths in all three functions.
Makes progress towards #1692

Fix `FromBytes::read_from_suffix` return type; remove panic paths

---

src/lib.rs
src/util/macro_util.rs
zerocopy-derive/Cargo.toml
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/ui-msrv/enum.stderr
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-msrv/union.stderr
zerocopy-derive/tests/ui-nightly/enum.stderr
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-nightly/union.stderr
zerocopy-derive/tests/ui-stable/enum.stderr
zerocopy-derive/tests/ui-stable/struct.stderr
zerocopy-derive/tests/ui-stable/union.stderr

On Rust toolchains 1.78.0 or later, use
`#[diagnostic::on_unimplemented]` to improve the error message emitted when `IntoBytes` is derived on a type with inter-field padding.

[derive] Improve IntoBytes error messages

---

src/error.rs
src/pointer/ptr.rs
src/ref.rs
src/util/mod.rs

Permit callers to prove at compile time that alignment errors are unreachable for unaligned destination types. This permits them to infallibly ignore this error condition.

Encode infallible alignment errors in types

---

src/deprecated.rs
src/error.rs
src/ref.rs

[Ref] Remove unaligned constructors

---

src/lib.rs

See #1292
Makes progress towards #671

[doc] Document rustc type privacy bug

---

src/error.rs
src/lib.rs
src/ref.rs

Wherever alignment errors are possible, mention that it is possible to discard alignment errors when `Dst: Unaligned`.
Closes #1721

[docs] Make infallible align errors discoverable

---

src/lib.rs

Add TryFromBytes::try_read_from_{prefix,suffix}

---

zerocopy-derive/src/enum.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/enum_try_from_bytes.rs
zerocopy-derive/tests/struct_try_from_bytes.rs
zerocopy-derive/tests/union_try_from_bytes.rs

Also makes the signatures of is_bit_valid generated for structs, unions, and enums the same.

Rename generic param to avoid name collision

---

tools/update-ui-test-files.sh

This change makes it easier to copy+paste from the script when working manually, which is a common workflow.

[tools] Refactor update-ui-test-files.sh

---

src/lib.rs

Add TryFromBytes::try_{ref,mut}_from_{bytes,prefix,suffix}_with_elems

---

src/byteorder.rs

[byteorder] Implement additional ops for native RHSs

---

zerocopy-derive/src/enum.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/src/repr.rs
zerocopy-derive/tests/ui-msrv/enum.stderr
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-msrv/union.stderr
zerocopy-derive/tests/ui-nightly/enum.rs
zerocopy-derive/tests/ui-nightly/enum.stderr
zerocopy-derive/tests/ui-nightly/struct.rs
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-nightly/union.rs
zerocopy-derive/tests/ui-nightly/union.stderr
zerocopy-derive/tests/ui-stable/enum.stderr
zerocopy-derive/tests/ui-stable/struct.stderr
zerocopy-derive/tests/ui-stable/union.stderr

Represent the result of parsing all `#[repr(...)]` attributes on a type as a high-level type which is only capable of representing valid combinations of `#[repr(...)]` attributes and processes them into a concise representation that's easier for high-level code to work with.
This prepares us to more easily fix https://github.com/google/zerocopy/issues/1748.
While we're here, we make a number of other improvements.
1) Errors are now converted to `TokenStream`s as late as possible rather than as early as possible, which was the previous behavior. This allows us to bail early when deriving an implied trait fails (e.g., deriving `TryFromBytes` when the user wrote `#[derive(FromZeros)]`).
2) Avoid re-computing some repr information in `TryFromBytes` enum support.

[derive] Overhaul repr parsing

---

src/lib.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/repr.rs
zerocopy-derive/tests/struct_to_bytes.rs
zerocopy-derive/tests/ui-msrv/msrv_specific.rs
zerocopy-derive/tests/ui-msrv/msrv_specific.stderr
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-msrv/union.stderr
zerocopy-derive/tests/ui-nightly/struct.rs
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-nightly/union.rs
zerocopy-derive/tests/ui-nightly/union.stderr
zerocopy-derive/tests/ui-stable/struct.stderr
zerocopy-derive/tests/ui-stable/union.stderr

Derive packed

---

zerocopy-derive/src/lib.rs
zerocopy-derive/tests/struct_to_bytes.rs
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-nightly/struct.rs
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/struct.stderr

[derive] Don't support IntoBytes on repr(Rust) types

---

.github/workflows/ci.yml
src/impls.rs

NEON intrinsics are not supported on aarch64 big endian targets. Change to use fall back types for big endian aarch64.
tested on aarch64_be-unknown-linux-gnu_ilp32 and aarch64_be-unknown-linux-gnu

aarch64 fix for big endian types

---

zerocopy-derive/src/lib.rs
zerocopy-derive/tests/struct_to_bytes.rs
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-nightly/struct.rs
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/struct.stderr

The Reference guarantees that, even in `repr(Rust)` structs, fields cannot overlap. This is sufficient to guarantee the soundness of implementing `IntoBytes` on some `repr(Rust)` structs.
Closes #1794

[derive] Support IntoBytes on repr(Rust) structs

---

src/lib.rs
tools/cargo-zerocopy/src/main.rs
zerocopy-derive/Cargo.toml
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/trybuild.rs
zerocopy-derive/tests/ui-msrv/union_into_bytes_cfg/union_into_bytes_cfg.rs
zerocopy-derive/tests/ui-msrv/union_into_bytes_cfg/union_into_bytes_cfg.stderr
zerocopy-derive/tests/ui-nightly/union_into_bytes_cfg/union_into_bytes_cfg.rs
zerocopy-derive/tests/ui-nightly/union_into_bytes_cfg/union_into_bytes_cfg.stderr
zerocopy-derive/tests/ui-stable/union_into_bytes_cfg/union_into_bytes_cfg.rs
zerocopy-derive/tests/ui-stable/union_into_bytes_cfg/union_into_bytes_cfg.stderr

[derive] IntoBytes on unions requires --cfg

---

POLICIES.md

Previously, we incorrectly stated that syn was the only dependency of zerocopy-derive.

[POLICIES] Update MSRV policy: multiple crate deps

---

src/lib.rs

Warn more loudly about IntoBytes on unions

---

zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs

Permit it to be passed either when compiling zerocopy-derive or when compiling the user's crate. This makes the --cfg play more nicely with different build systems.
Makes progress on #1792

Loosen --cfg zerocopy_derive_union_into_bytes

---

zerocopy-derive/src/lib.rs

The unstable feature [fmt-debug](https://doc.rust-lang.org/beta/unstable-book/compiler-flags/fmt-debug.html) allows to influence `derive(Debug)` implementations, for example by making it return an empty string. As the standard library also does not make any guarantees on the outputs of `derive(Debug)` , this change does replace the reliance on it by an explicit conversion to the variant name.

Add support for fmt-debug

---

src/lib.rs

No such guarantee exists for conversion between `Box<T>` and `Arc<T>` and the current [^1] implementation *always* creates a new allocation. I'm not aware of other container types for which the comment is correct.
[^1]: https://doc.rust-lang.org/1.81.0/src/alloc/sync.rs.html#1950-1970

Remove misleading doc-comment

---

zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/ui-msrv/enum.stderr
zerocopy-derive/tests/ui-nightly/enum.rs
zerocopy-derive/tests/ui-nightly/enum.stderr
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/enum.stderr
zerocopy-derive/tests/ui-stable/struct.stderr

Use `Self` in padding check instead of type name.
Fixes #1642
Makes progress towards #671

Fix type arity error in padding check

---

src/lib.rs
src/pointer/ptr.rs
src/util/macros.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs

Change argument type of `pointer_to_metadata` from `NonNull<Self>` to `*mut Self`, since the implementations of `pointer_to_metadata` do not actually require the argument to be non-null.
I anticipate this change will make future code less verbose, as many standard library APIs return raw pointers, not  `NonNull`; for example, `Box::into_raw`.

Relax `pointer_to_metadata` preconditions

---

.github/workflows/release-crate-version.yml
ci/release_crate_version.sh
githooks/pre-push

Sometimes we want to manually release, often when we are making a change and releasing it in the same commit. This makes that process easier.

[ci] Factor out "release crate versions" script

---

.github/workflows/roll-pinned-toolchain-versions.yml

0.8 has been published, and 0.7 is no longer actively developed.

[ci] Stop rolling toolchains on the 0.7 branch

---

.github/workflows/roll-pinned-toolchain-versions.yml

Pass `RUSTFLAGS='--cfg=zerocopy_derive_union_into_bytes'`

Fix roll-pinned-toolchain-versions

---

src/error.rs

[doc] Advise `err.to_string()` to address lifetime issues

---

src/impls.rs

The cited text is on the stable docs since a few months.

Cite stable docs for bit validity of numeric types

---

Cargo.toml
src/byteorder.rs
zerocopy-derive/Cargo.toml

The absence of these impls lead to the absence of `Hash` for the byteorder-aware numeric types.
Fixes #1871

Implement `Hash` for `ByteOrder` types

---

src/util/macros.rs

Improve ZST DST error message

---

src/layout.rs
src/pointer/ptr.rs
src/util/macro_util.rs
src/util/mod.rs
zerocopy-derive/src/lib.rs

Now that our MSRV is 1.65, we can clean up some code.
Makes progress on #67

Upgrade some code for MSRV 1.65

---

.github/workflows/ci.yml
Cargo.toml
src/layout.rs
src/pointer/ptr.rs
src/util/macro_util.rs
src/util/mod.rs
zerocopy-derive/Cargo.toml
zerocopy-derive/src/lib.rs

Now that our MSRV is 1.65, it unlocks upgrading some dependencies' versions.

Upgrade versions of some dependencies

---

src/impls.rs
src/lib.rs
src/pointer/mod.rs
src/pointer/ptr.rs
src/util/macro_util.rs
src/util/macros.rs
zerocopy-derive/src/enum.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs

Previously, we supported the `AtLeast` bound, which was used to describe a subset relationship in which `I: AtLeast<J>` implied that `I` as at least as restrictive as `J`. However, as described in #1866, this incorrectly models invariants as monotonic. In reality, invariants both provide guarantees but also *require* guarantees.
This commit takes a step in the direction of resolving #1866 by removing `AtLeast`. Uses of `AtLeast<Shared>` are replaced by a new `Reference` trait, which is implemented for `Shared` and `Exclusive`. This serves two purposes: First, it makes it explicit what this bound means. Previously, `AtLeast<Shared>` had an ambiguous meaning, while `Reference` means precisely that an invariant is either `Shared` or `Exclusive` and nothing else. Second, it paves the way for …

[pointer] Clarify semantics of aliasing invariants

---

zerocopy-derive/src/lib.rs

Explain why we only support concrete types so that future authors won't spuriously add support for them.

[derive] Document trivial_is_bit_valid

---

src/impls.rs
src/lib.rs
src/pointer/inner.rs
src/pointer/mod.rs
src/pointer/ptr.rs
zerocopy-derive/src/enum.rs
zerocopy-derive/src/output_tests.rs

`PtrInner` carries all invariants which are not controlled by type parameters. Since `PtrInner` does not promise to uphold aliasing, alignment, or validity, we can move some utility methods to `PtrInner` which previously were responsible for maintaining invariants orthogonal to their purpose.
Makes progress on https://github.com/google/zerocopy/issues/1892 (still needs to be fixed on v0.8.x)
Closes #1890

[pointer] Add separate `PtrInner`

---

src/pointer/invariant.rs
src/pointer/ptr.rs

[pointer] Make invariants opaque, more ergonomic

---

src/impls.rs
src/lib.rs
src/pointer/invariant.rs
src/pointer/mod.rs
src/pointer/ptr.rs
src/util/macro_util.rs
src/util/macros.rs
zerocopy-derive/src/enum.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/include.rs
zerocopy-derive/tests/struct_try_from_bytes.rs
zerocopy-derive/tests/union_try_from_bytes.rs

`AliasingSafe` is really about whether a pointer permits unsynchronized reads - either because the referent contains no `UnsafeCell`s or because the aliasing mode is `Exclusive`. Previously, `AliasingSafe` was not named consistent with this meaning, and was a function of a *pair* of types rather than of a single type. This commit fixes both oversights.
While we're here, we also add `Read` bounds in some places, allowing us to simplify many safety comments.

[pointer] Simplify AliasingSafe, rename to Read

---

src/pointer/invariant.rs
src/pointer/mod.rs
src/pointer/ptr.rs
src/util/macro_util.rs
src/util/mod.rs

For aliasing, use `Inaccessible`. For alignment and validity, use `Unknown`.

[pointer] Rename `Any` -> `Unknown`/`Inaccessible`

---

src/impls.rs
src/pointer/invariant.rs
src/pointer/ptr.rs
src/util/macro_util.rs
src/util/macros.rs
zerocopy-derive/src/enum.rs
zerocopy-derive/src/output_tests.rs

This commit adds a framework which supports encoding in the type system any `I -> I` mapping where `I` is any `Invariant` type. This permits us to make `cast_unsized`'s return value smarter, and as a result, allows us to remove a lot of `unsafe` code.
Makes progress on #1122

[pointer] Support generic invariant mapping

---

src/lib.rs

These tests depend on `src` being aligned to multiples of 2. With this commit, that dependency is explicitly enforced.

Fix flaky `TryFromBytes` tests

---

Cargo.toml
src/lib.rs
zerocopy-derive/Cargo.toml

These are causing PMEs in the presence of `-C link-dead-code`, which casues them to be monomorphized for `Self = ()`, thus producing the problematic ZSTy DST `[()]`.
Ref rust-lang/rust#131793
Fixes #1867

Remove deprecated `FromBytes::(mut_)slice_from` items

---

src/lib.rs
src/pointer/invariant.rs
src/pointer/mod.rs
src/pointer/ptr.rs
src/util/macro_util.rs
src/util/macros.rs

We eventually hope to make use of `#[marker]` traits once they're
stable. This permits us to test to make sure the feature is as we expect
and that our intended usage works.
---
This PR is on branch [ptr-overhaul](../tree/ptr-overhaul).
- #1913
- #1910
- #1911
- #1925

Use #[marker] on nightly in CI

---

.github/workflows/ci.yml
Cargo.toml
testutil/src/lib.rs
tools/cargo-zerocopy/src/main.rs
unsafe-fields/Cargo.toml
unsafe-fields/LICENSE-APACHE
unsafe-fields/LICENSE-BSD
unsafe-fields/LICENSE-MIT
unsafe-fields/src/lib.rs

Makes progress on #1931
---
This PR is on branch [unsafe-fields](../tree/unsafe-fields).
- #1929

[unsafe-fields] Initial commit

---

.github/workflows/ci.yml
Cargo.toml
src/error.rs
src/impls.rs
src/layout.rs
src/lib.rs
src/util/macro_util.rs
src/util/macros.rs
src/util/mod.rs
zerocopy-derive/Cargo.toml

Previously, we had avoided doing this because there wasn't any way to guarantee that we didn't make mistakes and render the wrong version for a particular named toolchain version.
In this commit, we take the pragmatic approach of renaming the named toolchain versions - in particular, we add a suffix which includes the toolchain version. This is fairly error-resistant for two reasons:
- At the definition site (in `Cargo.toml`), the name appears on the same line as the version, so mistakes should be obvious
- At the use site (in various `.rs` files), the name appears within a few lines of any `#[cfg_attr(doc_cfg, doc(cfg(...)))]` attribute, so mistakes should similarly be obvious
Release 0.8.7.
Closes #894

[doc] Render toolchain version detection in rustdoc

---

.github/workflows/ci.yml
Cargo.toml
unsafe-fields/Cargo.toml
unsafe-fields/src/lib.rs

Release 0.2.0.
Makes progress on #1931
---
This PR is on branch [unsafe-fields-zerocopy](../tree/unsafe-fields-zerocopy).
- #1960

[unsafe-fields] Add as_ref_checked

---

src/lib.rs

These tests depend on `src` being aligned to multiples of 2. With this commit, that dependency is explicitly enforced.

Fix flaky alignment tests

---

src/layout.rs
src/pointer/ptr.rs

If `try_cast_into` and `validate_cast_and_convert_metadata` are not inlined, then the compiler will include a panic in `validate_cast_and_convert_metadata`.
If these functions are inlined, then the panic can be optimized out.
Additional context can be found at https://github.com/google/zerocopy/issues/1661#issuecomment-2447948912

Inline layout validation and pointer cast code to optimize out panic

---

Cargo.toml
src/error.rs
zerocopy-derive/Cargo.toml

Relax `map_src` argument bound to `FnOnce`

---

src/layout.rs
src/pointer/ptr.rs

[Back-porting from #1997]
If `try_cast_into` and `validate_cast_and_convert_metadata` are not inlined, then the compiler will include a panic in `validate_cast_and_convert_metadata`.
If these functions are inlined, then the panic can be optimized out.

Always inline layout validation and pointer cast code to optimize out panics in `validate_cast_and_convert_metadata`

---

.github/workflows/backport-pr.yml

Closes #2014
---
This PR is on branch [backport-pr-github-action](../tree/backport-pr-github-action).
- #2017

[ci] Add GitHub Action to backport PR

---

src/error.rs

Relax `map_src` argument bound to `FnOnce` (#2012)

---

src/lib.rs

Add `FromBytes::read_from_io` and `IntoBytes::write_to_io`

---

Cargo.toml
README.md
src/impls.rs
src/lib.rs
src/util/macros.rs

Also extend `unsafe_impl` with support for adding arbitrary attributes to the impls.
Closes #1999

Add support for the unstable f16 and f128 types

---

zerocopy-derive/Cargo.toml

0.2.164 bumps the MSRV of libc beyond our crate's. By pinning libc to the last compatible version, we ensure that our CI can run without issue. Probably.

Pin `libc` version to 0.2.163

---

.github/workflows/ci.yml

This is triggered when the most recent commit in a PR has a commit message which contains the string `SKIP_CARGO_SEMVER_CHECKS=1` on its own line.
SKIP_CARGO_SEMVER_CHECKS=1
Closes #2083

[ci] Permit skipping cargo-semver-checks step

---

.github/workflows/ci.yml
src/impls.rs
src/lib.rs
src/util/macros.rs
src/util/mod.rs
src/wrappers.rs
tests/ui-nightly/diagnostic-not-implemented-known-layout.stderr
tests/ui-stable/diagnostic-not-implemented-known-layout.stderr
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/ui-msrv/mid_compile_pass.stderr
zerocopy-derive/tests/ui-nightly/mid_compile_pass.stderr
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/mid_compile_pass.stderr
zerocopy-derive/tests/ui-stable/struct.stderr

This is achieved by adding a `MaybeUninit` associated type to `KnownLayout`, whose layout is identical to `Self` except that it admits uninitialized bytes in all positions.
For sized types, this is bound to `mem::MaybeUninit<Self>`. For potentially unsized structs, we synthesize a doppelganger with the same `repr`, whose leading fields are wrapped in `mem::MaybeUninit` and whose trailing field is the `MaybeUninit` associated type of struct's original trailing field type. This type-level recursion bottoms out at `[T]`, whose `MaybeUninit` associated type is bound to `[mem::MaybeUninit<T>]`.
In the near term, we may remove `doc(hidden)` from our `MaybeUninit` wrapper. In doing so, we'd be quick-to-ship a gadget that extends the present capabilities of Rust. We might, then, be able to use …

Add initial support for unsized `MaybeUninit` wrapper type

---

zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/issue_2117.rs

As of nightly-2024-11-20 - specifically [1] - this triggers an `unexpected_cfgs` lint even when emitted in derive-generated code.
[1] https://github.com/rust-lang/rust/pull/132577
Fixes #2117

[derive] Don't emit #[cfg(coverage_nightly)]

---

zerocopy-derive/tests/issue_2117.rs

As of nightly-2024-11-20 - specifically [1] - this triggers an `unexpected_cfgs` lint even when emitted in derive-generated code.
[1] https://github.com/rust-lang/rust/pull/132577
Fixes #2117

[derive] Don't emit #[cfg(coverage_nightly)] (#2123)

---

src/util/macro_util.rs
zerocopy-derive/src/ext.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/struct_known_layout.rs

This commit revises the `KnownLayout` derive on `repr(C)` target structs to preserve the correct resolution of `Self` when constructing `__ZerocopyKnownLayoutMaybeUninit`. This type contains a `MaybeUninit` version of each of the target struct's field types. Previously, it achieved this by simply copying the tokens corresponding to field types from the definition of the target struct into the definition of `__ZerocopyKnownLayoutMaybeUninit`
However, on types like this:
```rust
#[repr(C)]
struct Struct([u8; Self::N]);
```
…this approach is insufficient. Pasted into `__ZerocopyKnownLayoutMaybeUninit`, `Self` ceases to refer to the target struct and instead refers to `__ZerocopyKnownLayoutMaybeUninit`.
To preserve `Self` hygiene, this commit defines a struct for projecting the field types of …

Practice good `Self` hygiene

---

src/lib.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/hash.rs
zerocopy-derive/tests/include.rs

The standard library's derive for `Hash` generates a recursive descent into the fields of the type it is applied to. This commit adds an alternative derive that generates an optimized, byte-oriented `Hash` implementation for types that implement `IntoBytes`. Instead of a recursive descent, the generated implementation makes a single call to `Hasher::write()` in both `Hash::hash()` and `Hash::hash_slice()`, feeding the hasher the bytes of the type or slice all at once.
Resolves #2075

[derive] Implement a IntoBytes-based Hash derive

---

src/lib.rs
src/util/macro_util.rs
src/util/macros.rs
src/util/mod.rs

Only use the `coverage_nightly` attribute in CI (ie, when `__ZEROCOPY_INTERNAL_USE_ONLY_NIGHTLY_FEATURES_IN_TESTS` is present).
Fixes #2286
gherrit-pr-id: I362bc7b83910e0e5112df895c559ff65d033766f

Only support coverage in CI

---

src/lib.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/eq.rs
zerocopy-derive/tests/include.rs

The standard library's derive for `PartialEq` generates a recursive descent into the fields of the type it is applied to. This commit adds a `ByteEq` derive that generates an optimized, byte-oriented `PartialEq` implementation -- and a corresponding `Eq` implementation -- for types that implement `IntoBytes`. Instead of a recursive descent, the generated implementation performs a single slice comparison of the bytes of the two values being compared.
Closes #2274

[derive] Implement an IntoBytes-based PartialEq/Eq derive

---

src/macros.rs
src/util/macro_util.rs
tests/ui-msrv/try_transmute_mut-src-not-frombytes.rs
tests/ui-msrv/try_transmute_mut-src-not-frombytes.stderr
tests/ui-nightly/try_transmute_mut-src-not-frombytes.rs
tests/ui-nightly/try_transmute_mut-src-not-frombytes.stderr
tests/ui-nightly/try_transmute_mut-src-not-intobytes.stderr
tests/ui-stable/try_transmute_mut-src-not-frombytes.rs
tests/ui-stable/try_transmute_mut-src-not-frombytes.stderr

Ensures that the source reference remains valid after the transmuted (and possibly mutated)  destination is dropped.
Makes progress on #2226

Enforce `Src: FromBytes` in `try_transmute_mut!`

---

src/pointer/invariant.rs

We previously used `AliasingMapping`s and `Inaccessible` to model
`UnsafeCell` agreement. This abuses the notion of a mapping since one
doesn't ever actually want to change the aliasing of a pointer (and
certainly not to `Inaccessible`) - really this was meant to model
pointer casts which should never be performed. In addition to being an
awkward fit, the presence of `Inaccessible` meant that code could not
assume that any `Aliasing` invariant permitted reading, and so we had to
add extra machinery to work around this.
Future commits will use a different, simpler model for denoting
`UnsafeCell` agreement or disagreement.
While we're here, make `Read` slightly more permissive, implemented for
`A: Aliasing, T: Immutable` rather than just `A: Reference, T:
Immutable`.
Makes progress on …

[pointer][invariant] Remove AliasingMapping, Inaccessible

---

zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/struct_known_layout.rs

[derive] Fix bug with KnownLayout on repr(packed)

---

.github/workflows/ci.yml

This is triggered when the most recent commit in a PR has a commit message which contains the string `SKIP_CARGO_SEMVER_CHECKS=1` on its own line.
SKIP_CARGO_SEMVER_CHECKS=1
Closes #2083
gherrit-pr-id: Iffcecec3b7abfd48a67011d5979aa075b68da0ba

[ci] Permit skipping cargo-semver-checks step (#2084)

---

.github/workflows/ci.yml
src/impls.rs
src/lib.rs
src/util/macros.rs
src/util/mod.rs
src/wrappers.rs
tests/ui-msrv/diagnostic-not-implemented-known-layout.stderr
tests/ui-nightly/diagnostic-not-implemented-known-layout.stderr
tests/ui-stable/diagnostic-not-implemented-known-layout.stderr
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/ui-msrv/mid_compile_pass.stderr
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-nightly/mid_compile_pass.stderr
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/mid_compile_pass.stderr
zerocopy-derive/tests/ui-stable/struct.stderr

This is achieved by adding a `MaybeUninit` associated type to `KnownLayout`, whose layout is identical to `Self` except that it admits uninitialized bytes in all positions.
For sized types, this is bound to `mem::MaybeUninit<Self>`. For potentially unsized structs, we synthesize a doppelganger with the same `repr`, whose leading fields are wrapped in `mem::MaybeUninit` and whose trailing field is the `MaybeUninit` associated type of struct's original trailing field type. This type-level recursion bottoms out at `[T]`, whose `MaybeUninit` associated type is bound to `[mem::MaybeUninit<T>]`.
Makes progress towards #1797
SKIP_CARGO_SEMVER_CHECKS=1
gherrit-pr-id: Idfc357094e28b54a15d947141241ca2da83dcc91

Add initial support for unsized `MaybeUninit` wrapper type (#2055)

---

src/impls.rs
src/lib.rs
src/macros.rs
src/util/macro_util.rs
tests/ui-msrv/try_transmute_mut-dst-not-tryfrombytes.stderr
tests/ui-nightly/try_transmute_mut-dst-not-tryfrombytes.stderr
tests/ui-stable/try_transmute_mut-dst-not-tryfrombytes.stderr

Consider that `MaybeUninit<u8>` is `TryFromBytes`. If a `&mut [u8]` is cast into a `&mut MaybeUninit<u8>`, then uninit bytes are written, the shadowed `&mut [u8]`'s referent will no longer be valid.
Makes progress towards #2226 and #1866.

Add `Self: IntoBytes` bound to `TryFromBytes::try_mut*`

---

src/pointer/invariant.rs
src/pointer/mod.rs
src/pointer/ptr.rs
src/util/macro_util.rs
src/util/macros.rs
src/util/mod.rs

Previously, validity was stored as part of the `I: Invariants` type
parameter on a `Ptr<T, I>`. In this commit, we migrate the validity to
being stored as the `V` in `Ptr<V, I>`; `I` now only stores aliasing and
alignment.
Bit validity is subtle, in that the pair of referent type and validity
invariant define a set of bit patterns which may appear in the `Ptr`'s
referent. By encoding the validity in the referent type instead of in
the `I` parameter, we ensure that the validity of the referent is
captured entirely by a single type parameter rather than by a pair of
two separate type parameters. This makes future changes (e.g. #1359)
easier to model.
This idea was originally proposed in https://github.com/google/zerocopy/issues/1866#issuecomment-2654625725
Makes progress on #1866
---
This …

[pointer] Store validity in the referent type

---

src/pointer/ptr.rs
zerocopy-derive/src/enum.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs

Now that #1122 is complete in #1896, `project` is redundant.
---
This PR is on branch [transmute-from](../tree/transmute-from).
- #2335
- #2339

[pointer] Remove Ptr::project method

---

src/pointer/inner.rs
src/pointer/invariant.rs
src/pointer/ptr.rs
tests/ui-msrv/ptr-is-invariant-over-v.rs
tests/ui-msrv/ptr-is-invariant-over-v.stderr
tests/ui-nightly/ptr-is-invariant-over-v.rs
tests/ui-nightly/ptr-is-invariant-over-v.stderr
tests/ui-stable/ptr-is-invariant-over-v.rs
tests/ui-stable/ptr-is-invariant-over-v.stderr

Previously, `Ptr<'a, T>` and `PtrInner<'a, T>` documented themselves to
be covariant in both `'a` and `T`. This was true for `PtrInner`, but not
for `Ptr`, which used GATs, which are invariant. This is also not the
desired variance: for `Exclusive` aliasing, the desired variance matches
that of `&mut` references - namely, covariant in `'a` but invariant in
`T`.
This commit fixes this by making `Ptr<'a, T>` and `PtrInner<'a, T>`
unconditionally covariant in `'a` and invariant in `T`.
---
This PR is on branch [transmute-from](../tree/transmute-from).
- #2335
- #2351

[pointer] Fix Ptr[Inner] variance

---

Cargo.toml
README.md
src/lib.rs
zerocopy-derive/Cargo.toml

Add jswrenn as an author in `Cargo.toml` files.
gherrit-pr-id: I50cc283e73af52a110de292c7fd92426fea21e26

[readme] Explain maintenance, thank contributors

---

Cargo.toml
README.md
src/lib.rs
zerocopy-derive/Cargo.toml

Add jswrenn as an author in `Cargo.toml` files.
gherrit-pr-id: I50cc283e73af52a110de292c7fd92426fea21e26

[readme] Explain maintenance, thank contributors (#2360)

---

Cargo.toml
src/impls.rs
src/lib.rs
src/pointer/mod.rs
src/pointer/ptr.rs
src/util/macro_util.rs
src/util/macros.rs
zerocopy-derive/src/enum.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs

Previously, we supported the `AtLeast` bound, which was used to describe a subset relationship in which `I: AtLeast<J>` implied that `I` as at least as restrictive as `J`. However, as described in #1866, this incorrectly models invariants as monotonic. In reality, invariants both provide guarantees but also *require* guarantees.
This commit takes a step in the direction of resolving #1866 by removing `AtLeast`. Uses of `AtLeast<Shared>` are replaced by a new `Reference` trait, which is implemented for `Shared` and `Exclusive`. This serves two purposes: First, it makes it explicit what this bound means. Previously, `AtLeast<Shared>` had an ambiguous meaning, while `Reference` means precisely that an invariant is either `Shared` or `Exclusive` and nothing else. Second, it paves the way for …

[pointer] Clarify semantics of aliasing invariants (#1889)

---

src/pointer/inner.rs
src/pointer/mod.rs
src/pointer/ptr.rs

`PtrInner` carries all invariants which are not controlled by type parameters. Since `PtrInner` does not promise to uphold aliasing, alignment, or validity, we can move some utility methods to `PtrInner` which previously were responsible for maintaining invariants orthogonal to their purpose.
Makes progress on #1892 (still needs to be fixed on v0.8.x) Closes #1890
gherrit-pr-id: I1c2d4a54bc1d73d3079d043c2bc393a8967f44f6

[pointer] Add separate PtrInner (#1891)

---

src/impls.rs
src/lib.rs
src/pointer/invariant.rs
src/pointer/mod.rs
src/pointer/ptr.rs
src/util/macro_util.rs
src/util/macros.rs
zerocopy-derive/src/enum.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/include.rs
zerocopy-derive/tests/struct_try_from_bytes.rs
zerocopy-derive/tests/union_try_from_bytes.rs

`AliasingSafe` is really about whether a pointer permits unsynchronized reads - either because the referent contains no `UnsafeCell`s or because the aliasing mode is `Exclusive`. Previously, `AliasingSafe` was not named consistent with this meaning, and was a function of a *pair* of types rather than of a single type. This commit fixes both oversights.
While we're here, we also add `Read` bounds in some places, allowing us to simplify many safety comments.
gherrit-pr-id: I88b9101a614459af3b062dc3d38142ba76427f34

[pointer] Simplify AliasingSafe, rename to Read (#1908)

---

src/pointer/invariant.rs
src/pointer/mod.rs
src/pointer/ptr.rs
src/util/macro_util.rs
src/util/mod.rs

For aliasing, use `Inaccessible`. For alignment and validity, use `Unknown`.
gherrit-pr-id: I6b21a2d3a712196aed8897780da405dbc4ac6da1

[pointer] Rename Any -> Unknown/Inaccessible (#1909)

---

.github/workflows/ci.yml

We already have the merge queue; running on push is redundant.
gherrit-pr-id: I48ecff7f2ed189bf87ba0dcb451345c0d0278b83

[ci] Don't run on push (#1882)

---

src/pointer/inner.rs
src/pointer/ptr.rs
tests/ui-msrv/ptr-is-invariant-over-v.rs
tests/ui-msrv/ptr-is-invariant-over-v.stderr
tests/ui-nightly/ptr-is-invariant-over-v.rs
tests/ui-nightly/ptr-is-invariant-over-v.stderr
tests/ui-stable/ptr-is-invariant-over-v.rs
tests/ui-stable/ptr-is-invariant-over-v.stderr

Previously, `Ptr<'a, T>` and `PtrInner<'a, T>` documented themselves to be covariant in both `'a` and `T`. This was true for `PtrInner`, but not for `Ptr`, which used GATs, which are invariant. This is also not the desired variance: for `Exclusive` aliasing, the desired variance matches that of `&mut` references - namely, covariant in `'a` but invariant in `T`.
This commit fixes this by making `Ptr<'a, T>` and `PtrInner<'a, T>` unconditionally covariant in `'a` and invariant in `T`.
gherrit-pr-id: I29f8429d9d7b14026313f030f8dc1e895a98ad56

[pointer] Fix Ptr[Inner] variance (#2351)

---

src/pointer/invariant.rs
src/pointer/mod.rs
src/pointer/ptr.rs
src/util/macro_util.rs
src/util/mod.rs
tests/ui-msrv/diagnostic-not-implemented-unaligned.stderr
tests/ui-nightly/diagnostic-not-implemented-unaligned.stderr
tests/ui-stable/diagnostic-not-implemented-unaligned.stderr
zerocopy-derive/tests/include.rs
zerocopy-derive/tests/struct_try_from_bytes.rs
zerocopy-derive/tests/ui-msrv/derive_transparent.stderr
zerocopy-derive/tests/ui-msrv/late_compile_pass.stderr
zerocopy-derive/tests/ui-msrv/msrv_specific.stderr
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-nightly/derive_transparent.stderr
zerocopy-derive/tests/ui-nightly/late_compile_pass.stderr
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/derive_transparent.stderr
zerocopy-derive/tests/ui-stable/late_compile_pass.stderr
zerocopy-derive/tests/ui-stable/struct.stderr
zerocopy-derive/tests/union_try_from_bytes.rs

This commit makes the following improvements:
- Removes the `Inaccessible` aliasing mode. This mode was not unsound,
but it was unnecessary in practice.
- Replaces `Unknown` with `Unaligned` for alignment.
- Replaces `Unknown` with `Uninit` for validity.
Finally, with the exception of `transparent_wrapper_into_inner`, this
commit ensures that all `Ptr` methods which modify the type or validity
of a `Ptr` are sound.
Previously, we modeled validity as "knowledge" about the `Ptr`'s
referent (see #1866 for a more in-depth explanation). In particular, we
assumed that it was always sound to "forget" information about a `Ptr`'s
referent in the same way in which it is sound to "forget" that a `Ptr`
is validly-aligned, converting a `Ptr<T, (_, Aligned, _)>` to a
`Ptr<T, (_, Unaligned, _)>`.
The …

[pointer] Improve soundness of invariant modeling

---

src/layout.rs
src/util/macro_util.rs

Since we currently can't roll our pinned nightly toolchain, and since
support for the avr target which initially caused us to notice this
issue was only added on nightly recently, this commit does not add a
regression test. That will be done later as part of #2400 once we are
able to roll our pinned nightly toolchain.
Makes progress on #2400
---
This PR is on branch [avr-artmega](../tree/avr-artmega).
- #2401

Support 16-bit target platforms

---

src/pointer/ptr.rs

---
This PR is on branch [ptr-validity](../tree/ptr-validity).
- #2406
- #2403
- #2407

[pointer] Group imports at the top of the file

---

src/pointer/invariant.rs
src/pointer/mod.rs
src/pointer/ptr.rs
src/util/macro_util.rs

---
This PR is on branch [ptr-validity](../tree/ptr-validity).
- #2406
- #2408
- #2403
- #2409

[pointer] Remove ReadReason from Read trait

---

src/impls.rs
src/pointer/ptr.rs

Rename `into_exclusive_or_post_monomorphization_error` to
`into_exclusive_or_pme` for brevity.
---
This PR is on branch [ptr-validity](../tree/ptr-validity).
- #2406
- #2408
- #2403
- #2412

[pointer] Use PME acronym in method name

---

src/pointer/inner.rs

This significantly improves codegen on embedded targets, allowing many checks to be optimized out.

Inline try_cast_into()

---

src/macros.rs

This is intended to specifically support the cryptocorrosion project's
ppv-lite86 and groestl-aesni crates. Currently, these crates rely on
zerocopy's `derive` feature, which has caused long build times for some
dependents such as in [1].
The added macro is `#[doc(hidden)]`, and is only designed to support
ppv-lite86 and groestl-aesni. No semver stability guarantees are made
except that we will support the use cases of those specific crates.
[1] https://github.com/rust-random/rand/issues/1574#issuecomment-2636133946
---
This PR is on branch [cryptocorrosion-macro](../tree/cryptocorrosion-macro).
- #2418

[macro] Support deriving certain traits via macro

---

src/impls.rs
src/lib.rs
src/pointer/ptr.rs
src/pointer/transmute.rs
src/util/macros.rs
src/wrappers.rs

This permits us to remove the `KnownLayout` bounds from
`Ptr::transmute`, and thus to remove `Ptr::transmute_sized` entirely.
This also allows us to remove the hand-rolled impl of `TryFromBytes` for
`ManuallyDrop<T>`, replacing it with an invocation of
`impl_for_transmute_from!`.
---
- #2428
- #2423
- #2421
- #2427

[pointer] SizeEq supports raw pointer transmutes

---

src/impls.rs
src/lib.rs
src/pointer/transmute.rs
tests/ui-nightly/diagnostic-not-implemented-unaligned.stderr
tests/ui-stable/diagnostic-not-implemented-unaligned.stderr
zerocopy-derive/tests/ui-nightly/derive_transparent.stderr
zerocopy-derive/tests/ui-nightly/late_compile_pass.stderr
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/derive_transparent.stderr
zerocopy-derive/tests/ui-stable/late_compile_pass.stderr
zerocopy-derive/tests/ui-stable/struct.stderr

Closes #1253
---
- #2428
- #2423
- #2421

Implement traits for Cell

---

src/impls.rs
src/lib.rs
src/pointer/transmute.rs
src/wrappers.rs
tests/ui-nightly/diagnostic-not-implemented-unaligned.stderr
tests/ui-stable/diagnostic-not-implemented-unaligned.stderr
zerocopy-derive/tests/ui-nightly/derive_transparent.stderr
zerocopy-derive/tests/ui-nightly/late_compile_pass.stderr
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/derive_transparent.stderr
zerocopy-derive/tests/ui-stable/late_compile_pass.stderr
zerocopy-derive/tests/ui-stable/struct.stderr

In #2408, we simplified the safety precondition of `unsafe_impl!`, but
did not remove safety proofs at call sites made redundant by that
simplification. This commit removes those now-obsolete proofs.
---
- #2428
- #2423
- #2421

Remove obsolete safety proofs

---

.github/workflows/ci.yml
src/lib.rs
src/util/mod.rs

---
This PR is on branch [ptr-kani](../tree/ptr-kani).
- #2444
- #2449

[kani] Use function contracts instead of proofs

---

src/pointer/transmute.rs

This language was made stale by the recent change to `PtrInner`'s
invariants.
---
- #2428
- #2435
- #2455

[transmute] Update TryTransmuteFromPtr proof

---

src/util/macro_util.rs
zerocopy-derive/src/enum.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/crate_path.rs

Read the `#[zerocopy(crate = "...")]` attribute (if present), and use the provided path in the derive output when referencing items exported from zerocopy. If the attribute isn't present, then `::zerocopy` will be used.
Attention is still needed on the test case. It currently functions on a subset of zerocopy traits using a [similar technique to serde](https://github.com/serde-rs/serde/blob/master/test_suite/tests/test_serde_path.rs).

[derive] Support `#[zerocopy(crate = "...")]` attribute

---

src/byteorder.rs
src/impls.rs
src/lib.rs
src/pointer/transmute.rs
src/util/macros.rs
src/util/mod.rs
src/wrappers.rs
tests/ui-msrv/invalid-impls/invalid-impls.stderr
tests/ui-nightly/invalid-impls/invalid-impls.rs
tests/ui-nightly/invalid-impls/invalid-impls.stderr
tests/ui-stable/invalid-impls/invalid-impls.stderr

Replace:
safety_comment! {
/// SAFETY:
/// ...
foo!();
bar!();
}
With:
// SAFETY: ...
const _: () = unsafe {
foo!();
bar!();
};
Remove the `safety_comment!` macro.
---
This PR is on branch [remove-safety-comment-macro](../tree/remove-safety-comment-macro).
- #2483

Replace safety_comment! with const blocks

---

src/lib.rs
src/split_at.rs
src/util/mod.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-nightly/struct.rs
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/struct.stderr

Previously, `SplitAt`'s methods returned `Option<(&(mut) Self, &(mut) Self::Trailing)>`, where `None` reflects an index that's either out of bounds, or results in the split parts overlapping in a problematic manner. This design conflated two failure conditions into one and, worse, presented an overly expensive and conservative API: dynamically checking for overlap is expensive, and there are many cases in which overlapping parts are *not* problematic, and this API could not scale to accommodate them all. 
`SplitAt`'s methods now return `Option<Split<&(mut) Self>>`, where `None` reflects an out-of-bounds index, and `Split<&(mut) Self>` encodes the possibly-overlapping parts. `Split<&(mut) Self>` provides methods for producing references to the split parts via both dynamic overlap checking …

Separate `SplitAt`'s bounds checking and overlap checking

---

.github/workflows/ci.yml
Cargo.toml
build.rs
ci/check_todo.sh
githooks/pre-push
src/byte_slice.rs
src/byteorder.rs
src/error.rs
src/impls.rs
src/layout.rs
src/lib.rs
src/pointer/inner.rs
src/pointer/ptr.rs
src/pointer/transmute.rs
src/ref.rs
src/split_at.rs
src/util/macro_util.rs
src/util/macros.rs
src/util/mod.rs
src/wrappers.rs
zerocopy-derive/src/ext.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/tests/priv_in_pub.rs
zerocopy-derive/tests/struct_try_from_bytes.rs
zerocopy-derive/tests/union_try_from_bytes.rs

This allows us to leave TODO comments for things that should be resolved
before a PR is merged, and have stronger guarantees that these will
actually be resolved. Previously, we've manually created GitHub PR
review comments for TODO comments, which has let some TODOs through by
accident, and is generally a waste of developer time.
---
This PR is on branch [ban-todo](../tree/ban-todo).
- #2511

Ban TODO comments, require FIXME comments

---

src/error.rs

These impls should not (and do not) reflect on the address of the source. Even if they were to display the source value, they should do so by debug/display-printing the source, not by explicitly dereferencing the pointer.
Fixes #2535

Remove `Deref` bound on `Display` and `Error` for `ValidityError`

---

Cargo.toml
src/lib.rs

Previously, x86 AVX-12 SIMD types were gated by the unstable
`stdarch_x86_avx512` feature. As of this writing, that feature has been
stabilized on 1.89.0-nightly, staged for inclusion in 1.89.0 when it is
released as stable.
This means that the `simd-nightly` Cargo feature, which gates
`stdarch_x86_avx512`, will now cause the `stable_features` lint to
trigger when compiling on x86.
This commit enables `expect(stable_features)` when compiling with
`simd-nightly` for x86. Once 1.89.0 is released as stable, we will
follow up with a commit which uses version detection to enable support
for AVX-12 types, and we will remove our use of the `stdarch_x86_avx512`
feature entirely.
Makes progress on #2583
---
This PR is on branch [simd-nightly-avx12](../tree/simd-nightly-avx12).
- #2584

Expect `stable_features` lint for stable SIMD types

---

.github/release.yml
.github/workflows/release-crate-version.yml
.github/workflows/roll-pinned-toolchain-versions.yml

Closes #2605
---
This PR is on branch [release-notes](../tree/release-notes).
- #2634

[ci] Hide some auto-gen'd PRs from release notes

---

Cargo.toml
src/lib.rs
src/ref.rs
src/util/mod.rs

Computes the size of an object of type `Self` with the given pointer metadata.
Makes progress towards #2541

Add `KnownLayout::size_for_metadata`

---

zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/src/repr.rs

Support `repr(u128)` and `repr(i128)` in `derive(IntoBytes)`

---

zerocopy-derive/src/output_tests.rs

Just so we get a nice output test diff on the follow-up PR. :-)
Makes progress towards #1112

Output test `derive(IntoBytes)` on structs with trailing slices

---

src/impls.rs
src/util/macros.rs

Implement traits for unsafe function values

---

src/layout.rs
src/lib.rs
src/util/macro_util.rs
src/util/mod.rs
zerocopy-derive/src/lib.rs
zerocopy-derive/src/output_tests.rs
zerocopy-derive/tests/struct_to_bytes.rs
zerocopy-derive/tests/ui-msrv/struct.stderr
zerocopy-derive/tests/ui-nightly/struct.rs
zerocopy-derive/tests/ui-nightly/struct.stderr
zerocopy-derive/tests/ui-stable/struct.stderr

For example:
#[repr(C)]
struct Example {
leading: u8,
trailing: [Trailing]
}
Makes progress towards #1112

`derive(IntoBytes)`: support `repr(C)` structs with explicit trailing slices
