- .github/workflows/ci.yml
- rustfmt.toml
- zerocopy-derive/tests/ui/late_compile_pass.rs
> [ci.yml] Fix formatting and check formatting in CI

- src/byteorder.rs
- src/lib.rs
- zerocopy-derive/src/lib.rs
- zerocopy-derive/src/repr.rs
- zerocopy-derive/tests/hygiene.rs
- zerocopy-derive/tests/struct_as_bytes.rs
- zerocopy-derive/tests/struct_from_bytes.rs
- zerocopy-derive/tests/struct_unaligned.rs
- zerocopy-derive/tests/ui/late_compile_pass.stderr
- zerocopy-derive/tests/union_as_bytes.rs
- zerocopy-derive/tests/union_from_bytes.rs
- zerocopy-derive/tests/union_unaligned.rs
> Standardize import style

- src/lib.rs
- zerocopy-derive/src/repr.rs
> [derive] Fix Clippy warnings

- src/lib.rs
- zerocopy-derive/src/repr.rs
> Fix Clippy warnings

- src/byteorder.rs
- src/lib.rs
> Deny more Clippy lints

- src/lib.rs
- zerocopy-derive/src/lib.rs
> Fix Clippy lints

- .github/workflows/ci.yml
Add a CI job to run the clippy linting software.
Fixes #49
> [ci.yml] Add clippy_check job

- README.md
- generate-readme.sh
> Fix typo in README.md

- src/lib.rs
Signed-off-by: Ryan Russell <git@ryanrussell.org>
Small readability fixups in comments. No functional changes.
> docs: readability fixups

- .github/workflows/ci.yml
> [CI] Clean up ci.yml

- .github/workflows/ci.yml
- src/lib.rs
- zerocopy-derive/src/lib.rs
> Deny warnings in CI

- .github/workflows/ci.yml
> [CI] Check formatting of UI tests

- CONTRIBUTING.md
> [CONTRIBUTING.md] Clean up

- .github/workflows/ci.yml
- src/lib.rs
- zerocopy-derive/src/lib.rs
- zerocopy-derive/tests/ui/enum.stderr
> [CI] Roll nightly toolchain to 2022-10-17

- .github/workflows/ci.yml
> [CI] Use -Zmiri-symbolic-alignment-check

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Update to 2021 edition

- .github/workflows/ci.yml
- Cargo.toml
- src/lib.rs
- zerocopy-derive/src/lib.rs
> [CI] Check that docs are generated successfully

- Cargo.toml
> Publish 0.7.0-alpha.1

- src/lib.rs
> Add tests for trait object safety

- generate-readme.sh
> [generate-readme.sh] Fix typo in copyright comment

- src/lib.rs
> Test that some types don't implement some traits

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.7.0-alpha.2

- src/lib.rs
> Clean up allow(dead_code)

- src/derive_util.rs
> Mark zerocopy-derive utility macros as doc(hidden)

- .github/workflows/ci.yml
- Cargo.toml
- zerocopy-derive/Cargo.toml
> Use a single Cargo workspace

- README.md
- src/byteorder.rs
- src/lib.rs
- zerocopy-derive/src/lib.rs
- zerocopy-derive/tests/enum_from_bytes.rs
- zerocopy-derive/tests/enum_from_zeroes.rs
- zerocopy-derive/tests/hygiene.rs
- zerocopy-derive/tests/paths_and_modules.rs
- zerocopy-derive/tests/priv_in_pub.rs
- zerocopy-derive/tests/struct_from_bytes.rs
- zerocopy-derive/tests/struct_from_zeroes.rs
- zerocopy-derive/tests/ui-msrv/derive_transparent.stderr
- zerocopy-derive/tests/ui-msrv/enum.stderr
- zerocopy-derive/tests/ui-msrv/late_compile_pass.stderr
- zerocopy-derive/tests/ui-stable/derive_transparent.stderr
- zerocopy-derive/tests/ui-stable/enum.stderr
- zerocopy-derive/tests/ui-stable/late_compile_pass.stderr
- zerocopy-derive/tests/ui/derive_transparent.rs
- zerocopy-derive/tests/ui/derive_transparent.stderr
- zerocopy-derive/tests/ui/enum.rs
- zerocopy-derive/tests/ui/enum.stderr
- zerocopy-derive/tests/ui/late_compile_pass.rs
- zerocopy-derive/tests/ui/late_compile_pass.stderr
- zerocopy-derive/tests/union_from_bytes.rs
- zerocopy-derive/tests/union_from_zeroes.rs
- zerocopy-derive/tests/util.rs
> Introduce FromZeroes trait

- src/lib.rs
Make some minor formatting changes and resolve #132.
Closes #132
> Clean up trait doc comments

- Cargo.toml
- src/lib.rs
- tests/trybuild.rs
- tests/ui-msrv/transmute-illegal.stderr
- tests/ui-stable/transmute-illegal.stderr
- zerocopy-derive/Cargo.toml
- zerocopy-derive/src/repr.rs
- zerocopy-derive/tests/trybuild.rs
- zerocopy-derive/tests/ui-msrv/derive_transparent.stderr
- zerocopy-derive/tests/ui-msrv/enum.stderr
- zerocopy-derive/tests/ui-msrv/late_compile_pass.stderr
- zerocopy-derive/tests/ui-msrv/struct.stderr
- zerocopy-derive/tests/ui-msrv/union.stderr
- zerocopy-derive/tests/ui-stable/derive_transparent.stderr
- zerocopy-derive/tests/ui-stable/enum.stderr
Also update the versions of the stable and nightly compiler toolchains that are pinned in CI.
> Update MSRV to 1.65.0

- src/lib.rs
> Clarify Unalign ABI guarantees

- .github/workflows/ci.yml
> [ci] Run `apt-get update` before `install`

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.7.0-alpha.4

- .github/workflows/ci.yml
- src/lib.rs
> [ci] Run Clippy with --tests

- src/lib.rs
- zerocopy-derive/src/lib.rs
> Clean up one TODO, enable more Clippy lints

- .github/workflows/ci.yml
> [CI] Run on push to v0.6.x

- zerocopy-derive/Cargo.toml
- zerocopy-derive/src/repr.rs
> Migrate to syn-2 (#166)

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.6.2

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.6.3-alpha

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.6.3

- zerocopy-derive/src/lib.rs
> [derive] Use fully-qualified path for Sized

- src/lib.rs
> Document some unsafe blocks

- .github/workflows/ci.yml
> [CI] Use bash globstar for formatting

- README.md
- src/lib.rs
> [doc] Fix capitalization of a link

- src/lib.rs
Doesn't actually resolve #2 in the sense of doing the task listed in the TODO, but closes it since we don't need a separate issue to track this.
Closes #2
> Update TODO comment to link directly to Rust issue

- .github/workflows/ci.yml
> [CI] Only grant CI action "read" permission

- .github/workflows/ci.yml
> [CI] Test on riscv64gc-unknown-linux-gnu target

- .github/workflows/ci.yml
> [CI] Test on s390x-unknown-linux-gnu target

- .github/workflows/ci.yml
> [CI] Test on mips targets

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.7.0

- README.md
- src/lib.rs
> Minor documentation cleanup

- .github/workflows/ci.yml
> [CI] Increase network retries to make failures less common

- .github/workflows/ci.yml
> [CI] Document private and hidden items

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.7.2

- src/lib.rs
> Reflow one comment

- .github/dependabot.yml
> [CI] Configure dependabot commit message prefix

- src/lib.rs
> Simplify AsAddress impls

- .github/workflows/ci.yml
- src/lib.rs
> [CI] Only run Clippy on nightly

- .github/workflows/ci.yml
> [CI] Use cargo-semver-checks to check backwards-compatibility

- tests/ui-stable/invalid-impls/invalid-impls.stderr
> [UI tests] Add missing stderr file

- Cargo.toml
- README.md
- src/lib.rs
- zerocopy-derive/Cargo.toml
> [docs] Improve crate-level docs

- src/lib.rs
> fix: fix up broken link

- src/lib.rs
> [docs] Fix broken doc link

- .github/workflows/ci.yml
- src/byteorder.rs
- src/lib.rs
> [ci] Run byteorder tests under Kani

- src/lib.rs
...in `test_validate_cast_and_convert_metadata`
> [tests] Test more failure conditions

- src/lib.rs
> Fixed TODO comment placement

- .github/workflows/ci.yml
Upon merging, @joshlf will need to update branch protection settings.
> Add job to signal to branch protection that all other jobs have succeeded.

- Cargo.toml
- zerocopy-derive/Cargo.toml
> [trybuild] Update dep to 1.0.85

- POLICIES.md
- README.md
- src/lib.rs
Document our policies on soundness and MSRV.
> [POLICIES.md] Initial commit

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.7.9

- Cargo.toml
- src/third_party/rust/README.fuchsia
- zerocopy-derive/Cargo.toml
> [third-party][rust] Add README.fuchsia file

- Cargo.toml
> [ci] Roll pinned nightly toolchain

- .github/workflows/ci.yml
https://github.com/rust-lang/miri/issues/3125
> [ci] Work around Miri bug on aarch64 targets

- Cargo.toml
- src/byteorder.rs
- zerocopy-derive/Cargo.toml
> [byteorder] Minor doc improvements

- Cargo.toml
- zerocopy-derive/tests/ui-nightly/struct.rs
- zerocopy-derive/tests/ui-nightly/struct.stderr
- zerocopy-derive/tests/ui-nightly/union.stderr
Also roll pinned nightly to 2023-10-26.
> [derive][tests] Fix KnownLayout test

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.7.18

- .github/workflows/ci.yml
- tests/ui-msrv/transmute-mut-const.stderr
- tests/ui-nightly/transmute-mut-const.stderr
- tests/ui-stable/transmute-mut-const.stderr
> [ci] Don't deny warnings in UI tests

- Cargo.toml
- src/lib.rs
- zerocopy-derive/Cargo.toml
> [simd] Add support for new x86[_64] types

- cargo.sh
`cargo.sh` detects missing Rust toolchains and the `rust-src` component. When missing, it offers to install them automatically via `rustup`.
> [cargo.sh] Auto-install toolchains and components

- .github/workflows/ci.yml
- Cargo.toml
- src/lib.rs
- zerocopy-derive/Cargo.toml
> [doc] Use `doc(cfg(...))` in docs.rs

- Cargo.toml
- zerocopy-derive/Cargo.toml
This will include https://github.com/google/zerocopy/pull/584.
> Release 0.7.23

- cargo.sh
> [cargo.sh] Set CARGO_TARGET_DIR for cargo metadata

- src/lib.rs
- src/third_party/rust/layout.rs
- src/util.rs
> Use allow(unused) instead of underscore prefix

- src/lib.rs
- src/macros.rs
> Implement `TryFromBytes` for some external types 

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.7.28

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.7.29

- src/lib.rs
> Initial commit of `NoCell`

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.8.0-alpha.1

- CHANGELOG.md
- POLICIES.md
Closes #238
Makes progress on #679
> [docs] Add yank log

- CHANGELOG.md
> [yanks] Document yanks for #716

- .github/workflows/ci.yml
> [doc] Test `cargo doc` under `--no-default-features`

- src/pointer/ptr.rs
Allows expressing concepts like "The `Ptr` is at least shared-aliased, perhaps even exclusive-aliased".
> Add at-least-as-strict-as bounds to `Ptr` invariant system

- src/lib.rs
- src/pointer/ptr.rs
> Implement `TryFromBytes` for `[T; N]`

- .github/workflows/ci.yml
- zerocopy-derive/tests/ui-msrv/struct.stderr
- zerocopy-derive/tests/ui-nightly/struct.stderr
- zerocopy-derive/tests/ui-stable/struct.stderr
Investigates the unexpected UI test diff in #795.
> [ci] Fix missing UI test checks in CI

- Cargo.toml
- src/lib.rs
- src/macros.rs
- src/pointer/ptr.rs
- tests/ui-msrv/transmute-mut-alignment-increase.stderr
- tests/ui-msrv/transmute-mut-const.stderr
- tests/ui-msrv/transmute-mut-size-decrease.stderr
- tests/ui-msrv/transmute-mut-size-increase.stderr
- tests/ui-msrv/transmute-ptr-to-usize.stderr
- zerocopy-derive/Cargo.toml
- zerocopy-derive/tests/enum_known_layout.rs
- zerocopy-derive/tests/enum_no_cell.rs
- zerocopy-derive/tests/struct_from_bytes.rs
- zerocopy-derive/tests/struct_from_zeros.rs
- zerocopy-derive/tests/struct_known_layout.rs
- zerocopy-derive/tests/struct_no_cell.rs
- zerocopy-derive/tests/struct_to_bytes.rs
- zerocopy-derive/tests/struct_try_from_bytes.rs
- zerocopy-derive/tests/struct_unaligned.rs
- zerocopy-derive/tests/union_from_bytes.rs
- zerocopy-derive/tests/union_from_zeros.rs
- zerocopy-derive/tests/union_known_layout.rs
- zerocopy-derive/tests/union_no_cell.rs
> Lower our MSRV to 1.59.0

- src/byteorder.rs
> [byteorder] Implement TryFromBytes

- .github/workflows/ci.yml
Run `cargo check --tests`, not just `cargo check`.
> [ci] Check with tests

- src/lib.rs
- src/pointer/mod.rs
- src/pointer/ptr.rs
> Implement `TryFromBytes` for pointers

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.8.0-alpha.5

- src/pointer/ptr.rs
> Relax type bounds in Ptr::from_maybe_uninit_ref

- src/lib.rs
- src/pointer/ptr.rs
> [ptr] Relax some method bounds

- .github/workflows/ci.yml
> [ci] Pin Kani to last known-good version

- zerocopy-derive/src/lib.rs
This allows us to define proc macros as functions that take an already-parsed `&DeriveInput` rather than just a `TokenStream` which must be parsed. This, in turn, allows us to pass an already-parsed `&DeriveInput` when one proc macro invokes another (e.g., when the derive for `FromBytes` invokes the derive for `FromZeros`) rather than needing to clone the `TokenStream`.
> [derive] Use macro to generate some scaffolding

- .github/workflows/ci.yml
- src/byteorder.rs
> [ci] Roll Kani version to 0.47.0

- .github/workflows/roll-pinned-toolchain-versions.yml
> [ci] Run `cargo fix` when rolling toolchains

- src/lib.rs
- src/pointer/ptr.rs
> Add `KnownLayout`, remove `Sized` from some APIs

- src/byteorder.rs
- src/lib.rs
- src/macros.rs
> Use KnownLayout in more APIs

- src/lib.rs
> Deprecate some `Ref` methods in favor of `KnownLayout`

- .github/workflows/roll-pinned-toolchain-versions.yml
> [ci] Pass dev and CI `--cfg` when rolling toolchain

- src/lib.rs
> Make TryFromBytes methods not #[doc(hidden)]

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.8.0-alpha.6

- README.md
- src/lib.rs
> Restructure crate-level 'Overview' documentation

- src/lib.rs
> Deprecate more Ref constructors

- src/lib.rs
> Remove underscores from now-used item names

- src/util.rs
Makes progress on https://github.com/google/zerocopy/issues/1009
> Implement `TransparentWrapper` for atomic types 

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.8.0-alpha.7

- Cargo.toml
- build.rs
- src/lib.rs
> Roll pinned nightly toolchain

- Cargo.toml
- src/lib.rs
- src/macro_util.rs
> [ci] Roll nightly toolchain

- src/deprecated.rs
- src/lib.rs
> Remove zeroing Ref constructors

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Release 0.8.0-alpha.8

- src/lib.rs
While we're here, replace some `bikeshed_xxx` `Ref` constructors with their non-`bikeshed` equivalents. It appears that we accidentally introduced complete duplication in our API, so these `bikeshed_xxx` constructors can simply be deleted.
> [FromBytes] Replace Ref with Ptr in some methods

- INTERNAL.md
- tools/cargo-zerocopy/src/main.rs
- tools/update-ui-test-files.sh
Update documentation to mention this new script.
Closes #1170
> [tools/update-ui-test-files.sh] Initial commit

- .github/workflows/release-crate-version.yml
> [release-crate-versions] Support arbitrary branches

- .github/workflows/roll-pinned-toolchain-versions.yml
> Roll pinned toolchain versions on v0.7.x

- Cargo.toml
- zerocopy-derive/Cargo.toml
> [Backport] Set manifest keywords and categories

- zerocopy-derive/src/ext.rs
- zerocopy-derive/src/repr.rs
This ensures that if they become unused, we will get a warning.
> [derive] Make some pub items pub(crate)

- src/lib.rs
- src/pointer/ptr.rs
- src/util.rs
The first return value is unchanged - it is the target of the cast. The second return value replaces the previous `split_at: usize`, and replaces it with a pointer to the prefix or suffix bytes as a `Ptr<[u8]>`.
This permits us to replace uses of `Ref` with direct uses of `Ptr` in some places.
> [pointer] Ptr::try_cast_into returns two Ptrs

- src/lib.rs
Require that `.into()` behaves identically to `.deref()`.
> Document `IntoByteSlice` safety invariants

- .github/actions/cache/action.yml
- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/dependency-review.yml
- .github/workflows/release-crate-version.yml
- .github/workflows/roll-pinned-toolchain-versions.yml
- .github/workflows/scorecard.yml
- CHANGELOG.md
- ci/check_all_toolchains_tested.sh
- ci/check_fmt.sh
- ci/check_job_dependencies.sh
- ci/check_msrv.sh
- ci/check_readme.sh
- ci/check_versions.sh
- githooks/pre-push
> Add missing copyright header comments

- src/lib.rs
> Factor out some duplicated code in FromBytes

- src/byteorder.rs
- src/deprecated.rs
- src/error.rs
- src/lib.rs
- src/ref.rs
> [ref] Change some `Ref` constructor names

- src/lib.rs
> Remove more unnecessary `Immutable` bounds from `FromBytes`

- src/lib.rs
> read_from_{prefix,suffix} return remaining bytes

- README.md
- src/lib.rs
> Include `try_transmute!` in crate-level overview

- README.md
- src/lib.rs
- src/ref.rs
> Document slice DSTs and size validity

- tests/trybuild.rs
> [trybuild] Only compile when `feature = "derive"`

- .github/workflows/ci.yml
This should help readability in GitHub's web UI.
> [ci] Make matrix names more concise

- zerocopy-derive/tests/deprecated.rs
- zerocopy-derive/tests/enum_from_bytes.rs
Follows up on #1332
Makes progress on #553
> [derive] Test derives on deprecated types

- src/macro_util.rs
> [macro_util] Add TODO comment to trailing_field_offset!

- .github/workflows/ci.yml
> [ci] Add Windows target

- .github/workflows/ci.yml
> [ci] Use cargo-semver-checks on stable, not nightly

- src/error.rs
> [error] Document validation order

- .github/workflows/ci.yml
Credit to @memark for landing obi1kenobi/cargo-semver-checks-action#82, which unblocked this!
Closes #357
> [ci] Run cargo-semver-checks on all targets

- testutil/Cargo.toml
> [testutil] Pin winapi-util to 0.1.8

- Cargo.toml
- src/lib.rs
- tests/ui-nightly/transmute-mut-dst-unsized.stderr
- tests/ui-nightly/transmute-mut-src-dst-unsized.stderr
- tests/ui-nightly/transmute-ref-dst-unsized.stderr
- tests/ui-nightly/transmute-ref-src-dst-unsized.stderr
- tests/ui-stable/transmute-mut-src-dst-not-references.stderr
- tests/ui-stable/transmute-mut-src-immutable.stderr
- tests/ui-stable/transmute-mut-src-not-a-reference.stderr
- tests/ui-stable/transmute-ref-src-dst-not-references.stderr
- tests/ui-stable/transmute-ref-src-not-a-reference.stderr
> Roll pinned nightly and stable toolchains

- README.md
- src/lib.rs
> [README] Link to 0.8 alpha draft release notes

- .github/workflows/ci.yml
- Cargo.toml
- build.rs
- src/error.rs
> [error] Implement `core::error::Error` for errors

- src/lib.rs
> [doc] 0x70 -> 0x10

- src/lib.rs
> Test elem count preservation for ZST slice tails

- src/lib.rs
- src/macros.rs
> doc: various pre-release improvements

- src/ref.rs
> [doc] Document `Ref` PMEs

- src/byte_slice.rs
> [doc] Fix broken links in `ByteSlice`

- src/byte_slice.rs
- src/ref.rs
> [byte_slice] Clean up docs and methods

- src/wrappers.rs
> [Unalign::update] Optimize when T is unaligned

- src/error.rs
> Implement `TryReadFrom::map_src`

- src/ref.rs
> [Ref] Clean up docs

- src/lib.rs
> Add TryFromBytes::try_ref_from_bytes_with_elems

- zerocopy-derive/src/enum.rs
- zerocopy-derive/src/lib.rs
- zerocopy-derive/src/output_tests.rs
- zerocopy-derive/tests/ui-msrv/enum.stderr
I didn't update the goldens because it was too hard
> Inline TryFromBytes derive for variant structs

- .gitignore
- tests/ui-msrv/include_value_not_from_bytes.stderr
- tests/ui-msrv/include_value_wrong_size.stderr
- tests/ui-nightly/include_value_not_from_bytes.rs
- tests/ui-nightly/include_value_not_from_bytes.stderr
- tests/ui-nightly/include_value_wrong_size.rs
- tests/ui-nightly/include_value_wrong_size.stderr
- tests/ui-stable/include_value_not_from_bytes.stderr
- tests/ui-stable/include_value_wrong_size.stderr
- zerocopy-derive/tests/enum_known_layout.rs
- zerocopy-derive/tests/enum_no_cell.rs
- zerocopy-derive/tests/struct_known_layout.rs
- zerocopy-derive/tests/struct_no_cell.rs
- zerocopy-derive/tests/union_known_layout.rs
- zerocopy-derive/tests/union_no_cell.rs
> Fix copyright headers

- zerocopy-derive/src/enum.rs
- zerocopy-derive/src/lib.rs
- zerocopy-derive/tests/enum_to_bytes.rs
- zerocopy-derive/tests/enum_try_from_bytes.rs
- zerocopy-derive/tests/struct_to_bytes.rs
- zerocopy-derive/tests/ui-msrv/struct.stderr
- zerocopy-derive/tests/ui-nightly/struct.rs
- zerocopy-derive/tests/ui-nightly/struct.stderr
- zerocopy-derive/tests/ui-stable/struct.stderr
> [derive] Correctly handle #[repr(align)] enums

- README.md
- src/lib.rs
> [docs] Link to Discord

- src/lib.rs
These methods used to spuriously take a `T: FromZeros` parameter.
> Fix FromZeros method signatures

- src/lib.rs
> Mark deprecated functions #[doc(hidden)]

- src/lib.rs
> Refactor try_read_from_xxx

- Cargo.toml
- zerocopy-derive/Cargo.toml
> Update to edition 2021

- Cargo.toml
- src/lib.rs
- src/ref.rs
- zerocopy-derive/Cargo.toml
This is a point in favor of landing #1021
> Fix broken doc links

- .github/workflows/ci.yml
> [ci] Enforce on PRs to v0.8.x

- src/lib.rs
- src/pointer/ptr.rs
- src/wrappers.rs
Also clean up some code for 0.9.
> Clean up some code for new MSRV

- .github/workflows/roll-pinned-toolchain-versions.yml
> Roll pinned toolchains on v0.8.x branch

- src/impls.rs
- src/lib.rs
- src/pointer/mod.rs
- src/pointer/ptr.rs
- zerocopy-derive/src/enum.rs
- zerocopy-derive/src/output_tests.rs
> [pointer] Fix soundness hole in read_unaligned

- unsafe-fields/Cargo.toml
Makes progress on #1931
---
This PR is on branch [unsafe-fields-cargo-toml](../tree/unsafe-fields-cargo-toml).
- #1959
> [unsafe-fields] Add Cargo.toml description

- .github/actions/cache/action.yml
- .github/workflows/ci.yml
> [CI] skip installation step when cache hit

- src/lib.rs
> docs: Add Portability section for TryFromBytes enum usage

- .github/workflows/backport-pr.yml
---
This PR is on branch [fix-backport-pr](../tree/fix-backport-pr).
- #2018
> [ci][backport-pr] Fetch all commits, configure git author

- src/layout.rs
> [layout] Update test documentation

- src/lib.rs
> Document that derives imply supertraits, where applicable.

- src/lib.rs
Makes progress on #158.
Co-authored-by: Joshua Liebow-Feeser <joshlf@users.noreply.github.com>
---
This PR is on branch [backport-io](../tree/backport-io).
- #2046
> Add `FromBytes::read_from_io` and `IntoBytes::write_to_io` (#2016)

- src/impls.rs
- src/lib.rs
- src/util/macros.rs
> Implement KnownLayout for f16 and f128

- src/lib.rs
> Fix soundness of FromBytes::read_from_io

- .github/workflows/release-crate-version.yml
> [release-new-crate-versions] Release on v0.8.x by default

- .github/workflows/backport-pr.yml
> [ci] Add GitHub Action to backport PR (backports #2017 and #2018)

- src/pointer/ptr.rs
- zerocopy-derive/src/enum.rs
- zerocopy-derive/src/lib.rs
- zerocopy-derive/src/output_tests.rs
---
This PR is on branch [ptr-validity](../tree/ptr-validity).
- #2403
- #2405
> [pointer] Replace project with cast_unsized_unchecked

- src/impls.rs
Makes progress on #1009
---
- #2423
- #2421
- #2427
- #2426
> Implement FromZeros for AtomicPtr

- .gitignore
---
This PR is on branch [gitignore](../tree/gitignore).
- #2443
> [git] Ignore VSCode workspace files

- .github/workflows/ci.yml
---
This PR is on branch [coverage-doc-tests](../tree/coverage-doc-tests).
- #2446
> [ci] Include doctests in coverage

- .github/workflows/ci.yml
- src/byte_slice.rs
- src/lib.rs
---
This PR is on branch [ptr-kani](../tree/ptr-kani).
- #2444
- #2451
> [byte_slice] Add Kani proofs

- zerocopy-derive/src/lib.rs
This allows us to simplify a number of call sites which don't make use
of every parameter that `impl_block` previously accepted.
---
This PR is on branch [derive-impl-block-builder](../tree/derive-impl-block-builder).
- #2456
> [derive] Replace impl_block with builder pattern

- zerocopy-derive/tests/unsafe_cell.rs
---
This PR is on branch [derive-unsafe-cell](../tree/derive-unsafe-cell).
- #2463
> [derive] Test with `UnsafeCell`s

- .github/workflows/ci.yml
- ci/check_todo.sh
---
This PR is on branch [fix-check-todo](../tree/fix-check-todo).
- #2514
> [ci] Install ripgrep dependency

- .vscode/settings.json
No problems have been detected in the workspace. 🎉
> Clean up compile errors in vscode
